#!/bin/bash

# Обновление библиотек
sleep 1 && echo "Обновление пакетов"
apt update &>/dev/null
apt upgrade -y &>/dev/null
sleep 2 && echo " Ок. Пакеты обновлены"

# Установка Docker'а если не устанолен
sleep 2 && echo "Проверяем наличие установленного Docker"
if command -v docker > /dev/null 2>&1; then
	sleep 2 && echo " Ок. Docker был ранее установлен"
else
    sleep 2 && echo "Устанавливаем Docker"
    apt install docker.io -y &>/dev/null
    sleep 2 && echo " Ок. Docker успешно установлен"
fi
usermod -a -G docker "$USER"

# Загрузка образа amnezia-wg-easy
sleep 2 && echo "Скачиваем образ wg-easy"
docker stop amnezia-wg-easy &>/dev/null
docker rm amnezia-wg-easy &>/dev/null
docker pull ghcr.io/w0rng/amnezia-wg-easy &>/dev/null
sleep 2 && echo " Ок. Образ amnezia-wg-easy скачен"

# Получение переменной ip адреса хоста для конфига контейнера amnezia-wg-easy
sleep 2 && echo "Получение ip сервера"
server_ip=$(hostname -I | awk '{print $1}')
sleep 2 && echo " Ок. $server_ip"

# Функция для проверки пароля
check_password() {
    local password="$1"

    # Проверка длины пароля (минимум 6 символов)
    if [ "${#password}" -lt 6 ]; then
        echo " Ошибка: Пароль должен быть не короче 6 символов"
        return 1
    fi

    # Проверка наличия хотя бы одной буквы
    if ! echo "$password" | grep -q '[a-zA-Z]'; then
        echo " Ошибка: Пароль должен содержать хотя бы одну букву"
        return 1
    fi

    # Проверка наличия хотя бы одной цифры
    if ! echo "$password" | grep -q '[0-9]'; then
        echo " Ошибка: Пароль должен содержать хотя бы одну цифру"
        return 1
    fi

    # Если все проверки пройдены
    return 0
}

# Функция для проверки порта
check_port() {
    local wg_port="$1"

    # Проверка, является ли порт числом
    if ! [[ "$wg_port" =~ ^[0-9]+$ ]]; then
        echo " Ошибка: Порт должен быть числом"
        return 1
    fi

    # Проверка диапазона порта (49152–65534)
    if [ "$wg_port" -lt 49152 ] || [ "$wg_port" -gt 65534 ]; then
        echo " Ошибка: Порт должен быть в диапазоне от 49152 до 65534"
        return 1
    fi

    return 0
}

# Цикл для ввода пароля
while true; do
    echo "Введите сложный пароль для веб интерфейса amnezia-wg-easy:"
    read -rs password

    # Проверка на пустой ввод
    if [ -z "$password" ]; then
        echo " Ошибка: Пароль не может быть пустым"
        continue
    fi

    # Проверка пароля
    if check_password "$password"; then
        # Создание хеша пароля
	output_wgpw=$(docker run --rm -it ghcr.io/w0rng/amnezia-wg-easy wgpw "$password")
	password_hash=$(echo "$output_wgpw" | cut -d '=' -f2 | tr -d '\r')
        echo " Ok. Пароль принят"
        break
    else
        echo " No. Попробуйте снова"
    fi
done

# Цикл для ввода порта
while true; do
    echo "Введите порт (от 49152 до 65534):"
    read wg_port

    # Проверка порта
    if check_port "$wg_port"; then
        # Увеличиваем порт на 1
        port=$((wg_port + 1))
        echo " Ок. Порт для AmneziaWG: $wg_port"
        echo " Ок. Порт для веб интерфейста: $port"
        break
    else
        echo " No. Попробуйте снова"
    fi
done

# Сохраняем  конфиги
sleep 2 && echo "Сохраняем конфиги в домашней директории"
cd || exit

# Сохраняем  конфиг на запуск wg
cat <<RUN_CONFIG > "run-amnezia-wg"
#!/bin/sh

sleep 2 && echo "-run-amnezia-wg: Запускаем контейнер amnezia-wg-easy"

docker run --detach \
  --name amnezia-wg-easy \
  --env LANG=ru \
  --env WG_HOST="$server_ip" \
  --env PASSWORD_HASH=$password_hash \
  --env PORT="$port" \
  --env WG_PORT="$wg_port" \
  --env WG_MTU=1400 \
  --env WG_PERSISTENT_KEEPALIVE=25 \
  --env WG_DEFAULT_DNS=1.1.1.1,1.0.0.1 \
  --env UI_TRAFFIC_STATS=true \
  --env USE_GRAVATAR=true \
  --volume ~/.amnezia-wg-easy:/etc/wireguard \
  --publish "$wg_port:$wg_port/udp" \
  --publish "$port:$port/tcp" \
  --cap-add NET_ADMIN \
  --cap-add SYS_MODULE \
  --sysctl 'net.ipv4.conf.all.src_valid_mark=1' \
  --sysctl 'net.ipv4.ip_forward=1' \
  --device=/dev/net/tun:/dev/net/tun \
  --restart unless-stopped \
  ghcr.io/w0rng/amnezia-wg-easy

sleep 2 && echo "-run-amnezia-wg: Ok. 🎉 amnezia-wg-easy запущен http://$server_ip:$port"
RUN_CONFIG

# Сохраняем  конфиг на остановку wg
cat <<STOP_CONFIG > "stop-amnezia-wg"
#!/bin/sh

sleep 2 && echo "-stop-amnezia-wg: Останавливаем контейнер amnezia-wg-easy"
docker stop amnezia-wg-easy &>/dev/null
docker rm amnezia-wg-easy &>/dev/null
sleep 2 && echo "-stop-amnezia-wg: Ok. amnezia-wg-easy контейнер остановлен"
STOP_CONFIG

# Сохраняем  конфиг на перезапуск wg
cat <<RERUN_CONFIG > "rerun-amnezia-wg"
#!/bin/sh

sleep 2 && echo "-rerun-amnezia-wg: Перезапускаем amnezia-wg-easy контейнер"
sh stop-amnezia-wg && sh run-amnezia-wg
sleep 2 && echo "-rerun-amnezia-wg: Ok. amnezia-wg-easy контейнер перезапущен"
RERUN_CONFIG

sleep 2 && echo " Ок. Конфиги run-wg, stop-wg и rerun-wg сохранены"

# Запуск контейнер wg-easy
sh run-amnezia-wg

$SHELL
