#!/bin/bash

# Очистка предыдущих установок
cd /root || exit
stop-ss >/dev/null 2>&1
systemctl disable ssserver >/dev/null 2>&1
rm -f shadowsocks-rust >/dev/null 2>&1
rm -rf /etc/shadowsocks-rust/config.json >/dev/null 2>&1
rm -f /etc/systemd/system/ssserver.service >/dev/null 2>&1
rm -f /sbin/sslocal /sbin/ssserver /sbin/ssmanager /sbin/ssurl >/dev/null 2>&1
rm -f /sbin/run-ss /sbin/stop-ss /sbin/rerun-ss /sbin/status-ss >/dev/null 2>&1
userdel shadowsocks >/dev/null 2>&1

# Обновление библиотек
echo "Обновление пакетов"
apt update >/dev/null 2>&1
apt upgrade -y >/dev/null 2>&1
echo " Ок. Пакеты обновлены"

# Установка необходимых пакетов и запуск служб
sleep 1 && echo "Установка необходимых пакетов..."
curl -s https://packagecloud.io/install/repositories/ookla/speedtest-cli/script.deb.sh | sudo bash >/dev/null 2>&1
apt install ufw pwgen lsof xz-utils apparmor apparmor-utils speedtest nano htop neofetch -y >/dev/null 2>&1
ufw allow 22 >/dev/null 2>&1
ufw --force enable >/dev/null 2>&1
echo " Ок. Пакеты установлены"

# Загрузка shadowsocks-rust
sleep 1 && echo "Загружаем shadowsocks-rust v1.22.0"
wget https://github.com/shadowsocks/shadowsocks-rust/releases/download/v1.22.0/shadowsocks-v1.22.0.x86_64-unknown-linux-gnu.tar.xz -P /opt/ >/dev/null 2>&1
tar xf /opt/shadowsocks-*-linux-gnu.tar.xz -C /sbin/ --owner=root --group=root >/dev/null 2>&1
rm /opt/shadowsocks-*-unknown-linux-gnu.tar.xz >/dev/null 2>&1
sleep 1 && echo " Ок. Загружено"

# Конфиги для оптимизации сервера shadowsocks в Linux
sleep 1 && echo "Оптимизация сервера shadowsocks"
cat >/etc/security/limits.conf <<LIMITS
root soft nofile 51200
root hard nofile 51200
LIMITS
ulimit -n 51200
cat >/etc/sysctl.d/00-shadowsocks.conf <<SYSCTL_CONF
fs.file-max = 51200

net.core.rmem_max = 67108864
net.core.wmem_max = 67108864
net.core.netdev_max_backlog = 250000
net.core.somaxconn = 4096

net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_fin_timeout = 30
net.ipv4.tcp_keepalive_time = 1200
net.ipv4.ip_local_port_range = 10000 65000
net.ipv4.tcp_max_syn_backlog = 8192
net.ipv4.tcp_max_tw_buckets = 5000
net.ipv4.tcp_fastopen = 3
net.ipv4.tcp_mem = 25600 51200 102400
net.ipv4.tcp_rmem = 4096 87380 67108864
net.ipv4.tcp_wmem = 4096 65536 67108864
net.ipv4.tcp_mtu_probing = 1
net.ipv4.tcp_congestion_control = hybla
SYSCTL_CONF
sysctl -p /etc/sysctl.d/00-shadowsocks.conf >/dev/null 2>&1
sleep 1 && echo " Ок. Оптимизация выполнена"

# Функция для проверки порта
check_port() {
    local port="$1"

    # Проверка, является ли порт числом
    if ! [[ "$port" =~ ^[0-9]+$ ]]; then
        sleep 1 && echo " Ошибка: Порт должен быть числом"
        return 1
    fi

    # Проверка диапазона порта (1–65534)
    if [ "$port" -lt 1 ] || [ "$port" -gt 65534 ]; then
        sleep 1 && echo " Ошибка: Порт должен быть в диапазоне от 1 до 65534"
        return 1
    fi

    # Проверка, занят ли порт
    if lsof -i :"$port" >/dev/null ; then
        echo "Ошибка: Порт $port уже занят"
        return 1
    fi

    return 0
}

# Цикл для ввода порта
while true; do
    sleep 1 && echo "Введите порт shadowsocks (1-65534):"
    read port

    # Проверка порта
    if check_port "$port"; then
        echo " Ок. Порт для shadowsocks: $port"
        sleep 1
        break
    else
        echo "Попробуйте снова"
    fi
done

# Генерация конфигов
sleep 1 && echo "Генерация конфигов"
# Конфиг shadowsocks (/etc/shadowsocks-rust/config.json)
mkdir -p /etc/shadowsocks-rust >/dev/null 2>&1
password=$(pwgen 32 1)
cat >/etc/shadowsocks-rust/config.json <<CONFIG
{
  "server": "0.0.0.0",
  "server_port": $port,
  "ipv6_first": false,
  "ipv6_only": false,
  "mode": "tcp_and_udp",
  "method": "aes-256-gcm",
  "password": "$password",
  "timeout": 300,
  "udp_timeout": 300,
  "udp_max_associations": 512
}
CONFIG

# Конфиг Systemd Unit
cat >/etc/systemd/system/ssserver.service <<CONFIG_SUSTEMD
[Unit]
Description=Shadowsocks-rust ssserver
Documentation=https://github.com/shadowsocks/shadowsocks/wiki
After=network.target
Wants=network.target

[Service]
ExecStart=/sbin/ssserver -c /etc/shadowsocks-rust/config.json
Restart=on-failure
User=shadowsocks
Group=shadowsocks
LimitNOFILE=51200
CapabilityBoundingSet=CAP_NET_BIND_SERVICE
AmbientCapabilities=CAP_NET_BIND_SERVICE

[Install]
WantedBy=multi-user.target
CONFIG_SUSTEMD

# Конфиг на запуск
cat <<RUN_CONFIG > "/sbin/run-ss"
#!/bin/sh
if systemctl is-active --quiet ssserver; then
    echo "Служба ssserver работает."
else
    echo "run-ss: Запускаем ssserver"
    systemctl start ssserver
    if systemctl is-active --quiet ssserver; then
        echo "run-ss: 🎉 ssserver запущен!"
    else
        echo "run-ss: Ошибка запуска службы! Введите status-ss для просмотра статуса"
    fi
fi
RUN_CONFIG

# Конфиг на на остановку
cat <<STOP_CONFIG > "/sbin/stop-ss"
#!/bin/sh
if systemctl is-active --quiet ssserver; then
    echo "stop-ss: Останавливаем ssserver"
    systemctl stop ssserver
    if ! systemctl is-active --quiet ssserver; then
        echo "stop-ss: Ok. ssserver остановлен!"
    fi
else
    echo "run-ss: ssserver не был запущен!"
fi
STOP_CONFIG

# Конфиг на перезапуск
cat <<RERUN_CONFIG > "/sbin/rerun-ss"
#!/bin/sh
echo "rerun-ss: Перезапускаем ssserver"
systemctl restart ssserver
if systemctl is-active --quiet ssserver; then
    echo "rerun-ss: Ok. ssserver перезапущен!"
else
    echo "rerun-ss: Ошибка перезапуска ssserver! Введите status-ss для просмотра статуса"
fi
RERUN_CONFIG

# Конфиг на получение статуса сервера
cat <<STATUS_CONFIG > "/sbin/status-ss"
#!/bin/sh
echo "status-ss: Выводим статус shadowsocks сервера"
systemctl status ssserver
STATUS_CONFIG
sleep 1 && echo " Ок. Конфиги сгененированы"

# Даём права на запуск конфигов управления docker-compose
chmod +x /sbin/run-ss /sbin/stop-ss /sbin/rerun-ss /sbin/status-ss

# Разрешение порта через файрвол ufw
sleep 1 && echo "Разрешаем порты $port/tcp $port/udp через файрвол ufw"
ufw allow "$port/tcp" >/dev/null 2>&1
ufw allow "$port/udp" >/dev/null 2>&1
ufw reload >/dev/null 2>&1
sleep 1 && echo " Ок. Портам выданы разрешения"

# Добавляем отдельного пользователя shadowsocks для запуска службы
sleep 1 && echo "Добавляем пользователя 'shadowsocks' для запуска службы"
useradd --system --home-dir /nonexistent --no-create-home --shell /usr/sbin/nologin shadowsocks >/dev/null 2>&1
sleep 1 && echo " Ок. Пользователя shadowsocks добавлен"

# Запуск контейнера ssserver-rust
systemctl daemon-reload
systemctl enable ssserver
run-ss

# Вывод данных для подключения по shadowsocks
echo "-------------------------------------------------------"
echo "Данные для подключения shadowsocks:"
echo "IP сервера: $(hostname -I | awk '{print $1}')"
echo "Порт: $port"
echo "Пароль: $password"
echo "-------------------------------------------------------"
