#!/bin/bash

# Обновление библиотек
echo "Обновление пакетов"
apt update >/dev/null 2>&1
apt upgrade -y >/dev/null 2>&1
echo " Ок. Пакеты обновлены"

cd || exit

# Очистка предыдущих установок
docker stop ssserver-rust  >/dev/null 2>&1
docker rm ssserver-rust  >/dev/null 2>&1
rm -f shadowsocks-rust shadowsocks-rust-config.json run-ss stop-ss rerun-ss >/dev/null 2>&1

# Установка необходимых пакетов и запуск служб
sleep 1 && echo "Установка необходимых пакетов..."
curl -s https://packagecloud.io/install/repositories/ookla/speedtest-cli/script.deb.sh | sudo bash >/dev/null 2>&1
apt install openssl ufw apparmor apparmor-utils speedtest nano htop neofetch -y >/dev/null 2>&1
echo "y" | ufw reset >/dev/null 2>&1
ufw allow 22 >/dev/null 2>&1
ufw --force enable >/dev/null 2>&1
echo " Ок. Пакеты установлены"
sleep 1 && echo "Проверяем установку Docker"
if ! command -v docker &> /dev/null; then
  sleep 1 && echo "Docker не установлен. Устанавливаем..."
  curl -sSL https://get.docker.com | sh >/dev/null 2>&1
  echo "Установка Docker завершена"
else
  sleep 1 && echo "Docker уже установлен"
fi
usermod -a -G docker "$USER"
service docker start >/dev/null 2>&1

# Конфиги для оптимизации сервера Shadowsocks в Linux
sleep 1 && echo "Оптимизация сервера Shadowsocks в Linux"
cat >/etc/security/limits.conf <<LIMITS
root soft nofile 51200
root hard nofile 51200
LIMITS
ulimit -n 51200
cat >/etc/sysctl.d/00-shadowsocks.conf <<SYSCTL_CONF
fs.file-max = 51200

net.core.rmem_max = 67108864
net.core.wmem_max = 67108864
net.core.netdev_max_backlog = 250000
net.core.somaxconn = 4096

net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_fin_timeout = 30
net.ipv4.tcp_keepalive_time = 1200
net.ipv4.ip_local_port_range = 10000 65000
net.ipv4.tcp_max_syn_backlog = 8192
net.ipv4.tcp_max_tw_buckets = 5000
net.ipv4.tcp_fastopen = 3
net.ipv4.tcp_mem = 25600 51200 102400
net.ipv4.tcp_rmem = 4096 87380 67108864
net.ipv4.tcp_wmem = 4096 65536 67108864
net.ipv4.tcp_mtu_probing = 1
net.ipv4.tcp_congestion_control = hybla
SYSCTL_CONF
sysctl -p /etc/sysctl.d/00-shadowsocks.conf >/dev/null 2>&1
sleep 1 && echo " Ок. Оптимизация выполнена"

# Функция для проверки порта
check_port() {
    local port="$1"

    # Проверка, является ли порт числом
    if ! [[ "$port" =~ ^[0-9]+$ ]]; then
        sleep 1 && echo " Ошибка: Порт должен быть числом"
        return 1
    fi

    # Проверка диапазона порта (1000–65534)
    if [ "$port" -lt 1000 ] || [ "$port" -gt 65535 ]; then
        sleep 1 && echo " Ошибка: Порт должен быть в диапазоне от 49152 до 65535"
        return 1
    fi

    return 0
}

# Цикл для ввода порта
while true; do
    sleep 1 && echo "Введите порт (от 1000 до 65534):"
    read port

    # Проверка порта
    if check_port "$port"; then
        echo " Ок. Порт для Shadowsocks: $port"
        sleep 1
        break
    else
        echo "Попробуйте снова"
    fi
done

# Генерация конфига shadowsocks-rust-config.json
sleep 1 && echo "Генерация конфигов shadowsocks-rust-config.json, run-ss, stop-ss, rerun-ss"
# Конфиг shadowsocks-rust-config.json
password="$(openssl rand -base64 32)"
cat >/root/shadowsocks-rust-config.json <<CONFIG
{
  "server": "0.0.0.0",
  "server_port": $port,
  "method": "aes-256-gcm",
  "password": "${password}",
  "mode": "tcp_and_udp"
}
CONFIG

# Конфиг на запуск
cat <<RUN_CONFIG > "run-ss"
#!/bin/sh
echo "run-ss: Запускаем ssserver-rust"
docker run --name ssserver-rust \
  --restart always \
  -p "${port}:8388/tcp" \
  -p "${port}:8388/udp" \
  -v /root/shadowsocks-rust-config.json:/etc/shadowsocks-rust/config.json \
  -dit ghcr.io/shadowsocks/ssserver-rust:latest
echo "run-ss: 🎉 Shadowsocks сервер ssserver-rust запущен!"
RUN_CONFIG

# Конфиг на на остановку
cat <<STOP_CONFIG > "stop-ss"
#!/bin/sh
echo "stop-ss: Останавливаем ssserver-rust"
docker stop ssserver-rust
docker rm ssserver-rust
echo "stop-ss: Ok. ssserver-rust остановлен"
STOP_CONFIG

# Конфиг на перезапуск wg
cat <<RERUN_CONFIG > "rerun-ss"
#!/bin/sh
echo "rerun-ss: Перезапускаем ssserver-rust"
./stop-ss 
./run-ss
echo "rerun-ss: Ok. ssserver-rust перезапущен"
RERUN_CONFIG
sleep 1 && echo " Ок. Конфиги сгененированы"

# Даём права на запуск конфигов управления docker-compose
chmod +x run-ss stop-ss rerun-ss

# Разрешение порта через файрвол ufw
sleep 1 && echo "Разрешаем порты $port/tcp $port/upd через файрвол ufw"
ufw allow "$port/tcp" >/dev/null 2>&1
ufw allow "$port/udp" >/dev/null 2>&1
ufw reload >/dev/null 2>&1
sleep 1 && echo " Ок. Портам выданы разрешения"

# Загрузка контейнера ssserver-rust
sleep 1 && echo "Загружаем docker контейнер ssserver-rust"
docker pull ghcr.io/shadowsocks/ssserver-rust:latest >/dev/null 2>&1
sleep 1 && echo " Ок. Загружено"

# Запуск контейнера ssserver-rust
./run-ss

# Получение переменных ip адреса сервера
server_ip=$(hostname -I | awk '{print $1}')

# Вывод данных для подключения
echo "------------------------------------"
echo "Данные для подключения:"
echo "IP сервера: $server_ip"
echo "Порт: $port"
echo "Пароль: $password"
echo "Шифрование: aes-256-gcm"
