#!/bin/bash
#
# https://github.com/jinndi/shadowsocks-tunnel-install
#
# Copyright (c) 2025 Jinndi <alncores@gmail.ru>
#
# Released under the MIT License, see the accompanying file LICENSE
# or https://opensource.org/licenses/MIT

set -e

## Пути исполняемых файлов
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

## Пути файлов:
# - исполняемый файл
path_ssserver="/sbin/ssserver"
# - файл службы
path_service="/etc/systemd/system/ssserver.service"
# - файл конфига shadowsocks-rust
path_config="/etc/shadowsocks-rust/config.json"
# - файл конфига sysctl
path_sysctl_config="/etc/sysctl.d/00-shadowsocks.conf"
# - файл конфига security limits
path_security_limits="/etc/security/limits.conf"
# - место сохранения текущего скрипта после установки сервера
path_script="/sbin/ss-server"

## Функции вывода сообщений:
# - шапка установщика
show_header() {
cat <<EOF

###################################################
#             shadowsocks-rust server             #
# GitHub: https://github.com/jinndi/wg-easy-bash  #
###################################################

EOF
}
# - стандартное через задержку
echomsg() {
  sleep 2; 
  echo
  echo "🟠 $1";
}
# - об успехе
echook() {
  echo "🟢 $1"
}
# - об ошибке
echoerr () {
  echo "🔴 $1"
}
# - об ошибке с выходом из скрипта
exiterr() {
  echo "🔴 Ошибка: $1" >&2
  exit 1
}


## Функции проверок возможности установки:
# - рут права
check_root() {
  if [ "$(id -u)" != 0 ]; then
    exiterr "Этот установщик должен быть запущен от имени root. Попробуйте 'sudo bash $0'"
  fi
}

# - способ запуска скрипта через bash а не sh
check_shell() {
  if readlink /proc/$$/exe | grep -q "dash"; then
    exiterr 'Этот установщик необходимо запускать с помощью «bash», а не «sh».'
  fi
}

# - вид дистрибутива ОС
check_os() {
  if grep -qs "ubuntu" /etc/os-release; then
    os="ubuntu"
    os_version=$(grep 'VERSION_ID' /etc/os-release | cut -d '"' -f 2 | tr -d '.')
  elif [[ -e /etc/debian_version ]]; then
    os="debian"
    os_version=$(grep -oE '[0-9]+' /etc/debian_version | head -1)
  else
    exiterr "Этот установщик поддерживает только дистрибутивы Ubuntu и Debian!"
  fi
}

# - версия дистрибутива ОС
check_os_ver() {
  if [[ "$os" == "ubuntu" && "$os_version" -lt 2004 ]]; then
    exiterr "Для использования этого установщика требуется Ubuntu 20.04 или более поздняя версия."
  fi
  if [[ "$os" == "debian" && "$os_version" -lt 11 ]]; then
    exiterr "Для использования этого установщика требуется Debian 11 или более поздняя версия."
  fi
}

# - поддержка версии ядра
check_kernel() {
  if [[ $(uname -r | cut -d "." -f 1) -eq 2 ]]; then
    exiterr "В системе установлено старое ядро, несовместимое с данным установщиком."
  fi
}

# - среда работы ОС
check_container() {
  if systemd-detect-virt -cq 2>/dev/null; then
    exiterr "Эта система работает внутри контейнера, который не поддерживается данным установщиком."
  fi
}

## Фунции проверок введенных данных пользователем:
# - порт
check_port() {
  # Проверка, является ли порт числом
  if ! [[ "$1" =~ ^[0-9]+$ ]]; then
    echoerr "Порт должен быть числом"
    return 1
  fi

  # Проверка диапазона порта (1–65535)
  if [ "$1" -lt 1 ] || [ "$1" -gt 65535 ]; then
    echoerr "Порт должен быть в диапазоне от 1 до 65535"
    return 1
  fi

  # Проверка, занят ли порт
  if lsof -i :"$1" >/dev/null ; then
    echoerr "Порт $1 уже занят"
    return 1
  fi

  return 0
}

install_pkgs(){
  echomsg "Установка зависимостей"
  export DEBIAN_FRONTEND=noninteractive
  (
    set -x
    apt-get -yqq update || apt-get -yqq update
    apt-get -yqq install pwgen lsof xz-utils >/dev/null
  ) || exiterr "'apt-get install' ошибка."
  echook "Зависимости установлены"
}

download_ssserver(){
  echomsg "Загрузка shadowsocks-rust ssserver v1.23.4"
  mkdir -p "$(dirname "$path_ssserver")"
  curl -L -o "$path_ssserver" https://raw.githubusercontent.com/jinndi/wg-easy-bash/refs/heads/main/ssserver
  if [[ ! -f "$path_ssserver" ]]; then
    exiterr "Ошибка загрузки shadowsocks-rust ssserver"
  fi
  chmod +x "$path_ssserver"
  echook "shadowsocks-rust ssserver v1.23.4 загружен"
}

optimization_configs(){
echomsg "Оптимизируем shadowsocks-rust сервер"
cat >"$path_security_limits" <<LIMITS
root soft nofile 51200
root hard nofile 51200
LIMITS
ulimit -n 51200
cat >"$path_sysctl_config" <<SYSCTL_CONF
fs.file-max = 51200
net.core.rmem_max = 67108864
net.core.wmem_max = 67108864
net.core.netdev_max_backlog = 250000
net.core.somaxconn = 4096
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_fin_timeout = 30
net.ipv4.tcp_keepalive_time = 1200
net.ipv4.ip_local_port_range = 10000 65000
net.ipv4.tcp_max_syn_backlog = 8192
net.ipv4.tcp_max_tw_buckets = 5000
net.ipv4.tcp_fastopen = 3
net.ipv4.tcp_mem = 25600 51200 102400
net.ipv4.tcp_rmem = 4096 87380 67108864
net.ipv4.tcp_wmem = 4096 65536 67108864
net.ipv4.tcp_mtu_probing = 1
net.ipv4.tcp_congestion_control = hybla
SYSCTL_CONF
sysctl -e -q -p "$path_sysctl_config" >/dev/null 2>&1
}

input_port(){
  while true; do
    read -rp "Введите порт (от 1 до 65535): " port
    if check_port "$port"; then
      break
    fi
  done
}

create_config(){
echomsg "Формируем конфиг shadowsocks-rust сервера"
password=$(pwgen 32 1)
mkdir -p "$(dirname "$path_config")"
cat >"$path_config" <<CONFIG
{
  "server": "0.0.0.0",
  "server_port": $port,
  "mode": "tcp_and_udp",
  "method": "aes-128-gcm",
  "password": "$password",
  "timeout": 120,
  "udp_timeout": 120,
  "udp_max_associations": 512
}
CONFIG
}

create_service(){
echomsg "Добавляем ssserver сервис"
cat >"$path_service" <<CONFIG_SUSTEMD
[Unit]
Description=Shadowsocks-rust ssserver
Documentation=https://github.com/shadowsocks/shadowsocks/wiki
After=network.target
Wants=network.target

[Service]
ExecStartPre=/bin/bash -c 'iptables -I INPUT 1 -p tcp --dport ${port} -j ACCEPT; iptables -I INPUT 1 -p udp --dport ${port} -j ACCEPT'
ExecStart=${path_ssserver} -c ${path_config}
ExecStopPost=/bin/bash -c 'iptables -D INPUT -p tcp --dport ${port} -j ACCEPT; iptables -D INPUT -p udp --dport ${port} -j ACCEPT'
Restart=on-failure
User=shadowsocks
Group=shadowsocks
LimitNOFILE=51200
CapabilityBoundingSet=CAP_NET_BIND_SERVICE
AmbientCapabilities=CAP_NET_BIND_SERVICE

[Install]
WantedBy=multi-user.target
CONFIG_SUSTEMD
}

add_user(){
  echomsg "Добавляем пользователя 'shadowsocks' для запуска сервиса"
  useradd --system --home-dir /nonexistent --no-create-home --shell /usr/sbin/nologin shadowsocks >/dev/null 2>&1
}

activate_ssserver(){
  echomsg "Активируем и запускаем ssserver службу"
  systemctl daemon-reload >/dev/null 2>&1
  systemctl enable --now ssserver >/dev/null 2>&1
  if systemctl is-active --quiet ssserver; then
    echook "shadowsocks-rust сервер запущен!"
  else
    echoerr "Ошибка запуска shadowsocks-rust! Введите 'journalctl -u ssserver -n 30' для просмотра лога"
  fi
}

switch_active_service(){
  systemctl daemon-reload >/dev/null 2>&1
  if systemctl is-active --quiet ssserver; then
    { systemctl stop ssserver && systemctl disable ssserver; } >/dev/null 2>&1
    if systemctl is-active --quiet ssserver; then
      echoerr "Ошибка остановки! Введите 'journalctl -u ssserver -n 30' для просмотра лога"
    else
      echook "Сервис успешно остановлен!"
    fi
  else
    systemctl enable --now ssserver >/dev/null 2>&1
    if systemctl is-active --quiet ssserver; then
      echook "Сервис успешно запущен!"
    else
      echoerr "Ошибка запуска! Введите 'journalctl -u ssserver -n 30' для просмотра лога"
    fi
  fi
  select_menu_option
}

reload_service(){
  systemctl daemon-reload >/dev/null 2>&1
  systemctl reload ssserver >/dev/null 2>&1
  if systemctl is-active --quiet ssserver; then
    echook "Сервис успешно перезапущен!"
  else
    echoerr "Ошибка перезапуска! Введите 'journalctl -u ssserver -n 30' для просмотра лога"
  fi
  select_menu_option
}

remove_ssserver(){
  echomsg "Удаление shadowsocks-rust файлов"
  systemctl stop ssserver
  systemctl disable ssserver
  rm -f "$path_config"
  rm -f "$path_service"
  rm -f "$path_ssserver"
  rm -f "$path_sysctl_config"  
  > "$path_security_limits"
  systemctl daemon-reload
  userdel shadowsocks
  echook "shadowsocks-rust успешно удален из системы!"
}

confirm_remove() {
  echo
  read -rp "Подтвердите удаление [y/N]: " remove
  until [[ "$remove" =~ ^[yYnN]*$ ]]; do
    echo "$remove: неверная опция."
    read -rp "Подтвердите удаление [y/N]: " remove
  done
}

confirm_reinstall() {
  echo
  read -rp "Подтвердите переустановку [y/N]: " reinstall
  until [[ "$reinstall" =~ ^[yYnN]*$ ]]; do
    echo "$reinstall: неверная опция."
    read -rp "Подтвердите переустановку [y/N]: " reinstall
  done
}

install_ssserver(){
  input_port
  install_pkgs
  download_ssserver
  create_config
  create_service
  add_user
  optimization_configs
  activate_ssserver

  # перемещам текущий скрипт, добавляем на него права
  mv "$(realpath "$0")" "$path_script"
  chmod +x "$path_script"

  # Данные для подключения
  echo
  echo "-------------------------------------------------------"
  echo "Детали для подключения по shadowsocks:"
  echo "Сервер IP: $(hostname -I | awk '{print $1}')"
  echo "Порт: $port"
  echo "Пароль: $password"
  echo "-------------------------------------------------------"
  echo

  read -n1 -r -p "Нажмите любую клавишу чтобы отобразить меню..."
  select_menu_option
}

select_menu_option() {
  local select_option="Выберите опцию:"
  sleep 2
  show_header
  if systemctl is-active --quiet ssserver; then
    echo "Статус: ✅ Работает"
    echo "$select_option"
    echo "  1) Остановить"
  else
    echo "Статус: ❌ Не активно"
    echo "$select_option"
    echo "  1) Запустить"
  fi
  echo "  2) Перезапустить"
  echo "  3) Удалить"
  echo "  4) Выход"

  read -rp "Опция: " option
  until [[ "$option" =~ ^[1-4]$ ]]; do
    echo "$option: неверная опция."
    read -rp "Опция: " option
  done

  case "$option" in
    1)
      switch_active_service
    ;;
    2)
      reload_service
    ;;
    3)
      confirm_remove
      if [[ "$remove" =~ ^[yY]$ ]]; then
        remove_ssserver
        rm -f "$path_script"
        exit 0
      else
        select_menu_option
      fi
    ;;
    4)
      exit exit 0
    ;;
  esac
}

if [[ -f "$path_ssserver" && -f "$path_service" ]]; then
  select_menu_option
else
  check_root
  check_shell
  check_kernel
  check_os
  check_os_ver
  check_container
  show_header
  read -n1 -r -p "Нажмите любую клавишу, чтобы начать установку..."
  install_ssserver
fi
