#!/bin/bash
#
# https://github.com/jinndi/wg-easy-bash
#
# Copyright (c) 2025 Jinndi <alncores@gmail.ru>
#
# Released under the MIT License, see the accompanying file LICENSE
# or https://opensource.org/licenses/MIT

## Пути исполняемых файлов
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

## Пути файлов:
# - папка в которую будет произведена установка
path_data_dir="$HOME/.wg-easy"
# - файл текущего скрипта
path_script="$path_data_dir/wg-easy"
# - ссылка на файл текущего скрипта
path_script_link="/usr/bin/wg-easy"
# - исполняемый файл tun2socks
path_tun2socks="$path_data_dir/tun2socks/tun2socks"
# - скрипт инициализации интерфейса tun2socks
path_tun2socks_init="$path_data_dir/tun2socks/tun2socks-init.sh"
# - папка настроек wireguard
path_data_wg_dir="$path_data_dir/wireguard"
# - файл docker compose сервисов
path_docker_compose_file="$path_data_dir/services.yml"
# - ссылка на файл systemd unit службы
path_systemd_unit_file="/etc/systemd/system/wg-easy.service"
# - файл настройки Caddy сервера
path_caddyfile="$path_data_dir/caddy/Caddyfile"
# - папка с данными  Caddy сервера
path_caddy_data="$path_data_dir/caddy/data"
# - папка с настройками Caddy сервера
path_caddy_config="$path_data_dir/caddy/config"
# - файл скрипта c сетевыми правилами iptables на запуск служб
path_iptables_active_script="$path_data_dir/iptables/active.sh"
# - файл скрипта для удаления ранее созданных iptables правил
path_iptables_delete_script="$path_data_dir/iptables/delete.sh"
# - файл конфига sysctl параметров 
path_sysctl_config="/etc/sysctl.d/99-wg-easy-bash.conf"

## Переменные настройки shadowsocks прокси интерфейса через tun2socks:
# - имя интерфейса
ss_tun_name="sstun"

# Ссылка на образ wg-easy
wg_easy_image="ghcr.io/wg-easy/wg-easy:latest"

## Пути в адресной строке браузера к UI интерфейсу (если указан домен):
# - по умолчанию
handle_path_ui="wg-easy"
# - для WireGuard через shadowsocks
handle_path_ui_ss="wg-easy-ss"

# DNS адреса по умолчанию для клиентов WireGuard (через запятую)
default_dns=1.1.1.1,8.8.8.8

## Объявление переменных задаваемых в процессе работы скрипта:
# - доменное имя либо адрес IP-адрес хоста
wg_host=""
# - e-mail адрес необходимый для получения SSL сертификата домена
email=""
# - tcp порт доступа к UI интерфейсу wg-easy
port=""
# - tcp порт доступа к UI интерфейсу wg-easy, shadowsocks тунннель
port_ss=""
# - udp порт WireGuard
wg_port=""
# - udp порт WireGuard, shadowsocks тунннель
wg_port_ss=""
# - диапазон IP-адресов клиентов WireGuard
default_address=""
# - диапазон IP-адресов клиентов WireGuard, shadowsocks тунннель
default_address_ss=""
# - IP-адрес shadowsocks сервера
ss_ip=""
# - порт shadowsocks сервера
ss_port=""
# - пароль к подключению по shadowsocks
ss_password=""
# - хеш пароля от UI интерфейса/ов wg-easy
password_hash=""
# - ссылка на UI интерфейс wg-easy
link_ui=""
# - ссылка на UI интерфейс wg-easy, shadowsocks тунннель
link_ui_ss=""
# - указал ли пользователя адрес домена
is_domain=""
# - ввел ли пользователя адрес shadowsocks сервера
is_shadowsocks=""

## Функции вывода сообщений:
# - шапка установщика
show_header() {
cat <<EOF

###################################################
#                  WG-EASY-BASH                   #
# GitHub: https://github.com/jinndi/wg-easy-bash  #
###################################################

EOF
}
# - стандартное через задержку
echomsg() {
  sleep 2; 
  echo
  echo "🟠 $1";
}
# - об успехе
echook() {
  echo "🟢 $1"
}
# - об ошибке
echoerr () {
  echo "🔴 $1"
}
# - об ошибке с выходом из скрипта
exiterr() {
  echo "🔴 Ошибка: $1" >&2
  exit 1
}


## Функции проверок возможности установки:
# - рут права
check_root() {
  if [ "$(id -u)" != 0 ]; then
    exiterr "Этот установщик должен быть запущен от имени root. Попробуйте 'sudo bash $0'"
  fi
}

# - способ запуска скрипта через bash а не sh
check_shell() {
  if readlink /proc/$$/exe | grep -q "dash"; then
    exiterr 'Этот установщик необходимо запускать с помощью «bash», а не «sh».'
  fi
}

# - вид дистрибутива ОС
check_os() {
  if grep -qs "ubuntu" /etc/os-release; then
    os="ubuntu"
    os_version=$(grep 'VERSION_ID' /etc/os-release | cut -d '"' -f 2 | tr -d '.')
  elif [[ -e /etc/debian_version ]]; then
    os="debian"
    os_version=$(grep -oE '[0-9]+' /etc/debian_version | head -1)
  else
    exiterr "Этот установщик поддерживает только дистрибутивы Ubuntu и Debian!"
  fi
}

# - версия дистрибутива ОС
check_os_ver() {
  if [[ "$os" == "ubuntu" && "$os_version" -lt 2004 ]]; then
    exiterr "Для использования этого установщика требуется Ubuntu 20.04 или более поздняя версия."
  fi
  if [[ "$os" == "debian" && "$os_version" -lt 11 ]]; then
    exiterr "Для использования этого установщика требуется Debian 11 или более поздняя версия."
  fi
}

# - поддержка версии ядра
check_kernel() {
  if [[ $(uname -r | cut -d "." -f 1) -eq 2 ]]; then
    exiterr "В системе установлено старое ядро, несовместимое с данным установщиком."
  fi
}

# - среда работы ОС (запрет установки из контейнера, например докер)
check_container() {
  if systemd-detect-virt -cq 2>/dev/null; then
    exiterr "Установка внути контейнера не поддерживается данным установщиком."
  fi
}

# Функция удаления предыдущих установок (без докера)
remove_install() {
  local is_show_info
  is_show_info="$1"

  if [[ -n "$is_show_info" ]]; then
    echomsg "Удаляем предыдущую установку"
  fi

  # Остановка сервисов с удаление всех задействованных контейнеров и образов
  if [[ -e "$path_docker_compose_file" ]]; then
    if systemctl is-active --quiet wg-easy; then
      systemctl disable --now wg-easy
    fi
  fi

  # Удаление ранее заданных iptables правил 
  if [[ -f "$path_iptables_delete_script" ]]; then
    if systemctl is-active --quiet wg-easy; then
      bash "$path_iptables_delete_script"
    fi
  fi

  # Удаление ссылки на скрипт управления
  if [[ -L "$path_script_link" ]]; then
    rm -f "$path_script_link"
  fi

  # Удаление папки данных
  if [[ -d "$path_data_dir" ]]; then
    rm -rf "$path_data_dir"
  fi

  # Удаление файла systemd unit службы
  if [[ -f "$path_systemd_unit_file" ]]; then
    rm -f "$path_systemd_unit_file"
  fi

  # Удаление sysctl кофига
  if [[ -f "$path_sysctl_config" ]]; then
    rm -f "$path_sysctl_config"
    sysctl --system > /dev/null 2>&1
  fi

  if [[ -n "$is_show_info" ]]; then
    echook "Файлы и службы/сервисы удалены"
  fi
}


# Функция установки необходимых пакетов программ
install_pkgs() {
  # ожидания пока система освободит блокировку пакетного менеджера (apt/dpkg)
  local count apt_lk apt_lk
  count=0
  apt_lk="/var/lib/apt/lists/lock"
  pkg_lk="/var/lib/dpkg/lock"
  while fuser "$apt_lk" "$pkg_lk" >/dev/null 2>&1 \
    || lsof "$apt_lk" >/dev/null 2>&1 || lsof "$pkg_lk" >/dev/null 2>&1; do
    [ "$count" = 0 ] && echo "Ожидаем, когда apt освободится..."
    [ "$count" -ge 100 ] && exiterr "Не удалось дождаться разблокировку apt/dpkg."
    count=$((count+1))
    printf '%s' '.'
    sleep 3
  done

  # Установка зависимостей
  echomsg "Установка зависимостей"
  export DEBIAN_FRONTEND=noninteractive
  (
    set -x
    apt-get -yqq update || apt-get -yqq update
  ) || exiterr "'apt-get update' ошибка."
  (
    set -x
    apt-get -yqq install iproute2 iptables curl lsof dnsutils grep sed \
    || apt-get -yqq install iproute2 iptables curl lsof dnsutils grep sed
  ) || exiterr "'apt-get install' ошибка."

  # Установка и запуск докера если ранее не установлен 
  if ! docker compose version &> /dev/null; then
    curl -sSL https://get.docker.com | sh
  fi
  systemctl start docker

  # Спуллить образ wg-easy если его нет
  if ! docker image inspect "$wg_easy_image" > /dev/null 2>&1; then
    docker pull "$wg_easy_image"
  fi

  echook "Зависимости установлены"
}


## Фунции проверок введенных данных пользователем:

# - имя домена
check_domain() {
  # Если строка не является доменом
  if [[ ! "$1" =~ ^([a-zA-Z0-9]([a-zA-Z0-9-]*[a-zA-Z0-9])?\.)+[a-zA-Z]{2,}$ ]]; then
    echoerr "Неккоректный адрес домена: $1"
    is_domain=""
    return 1
  fi
  is_domain="true"
  return 0
}

# - IPv4 адрес
check_IPv4() {
  # Проверка на формат IPv4
  if [[ ! "$1" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]]; then
    echoerr "Это не IPv4: $1"
    return 1
  fi

  # Проверка на диапазон для каждого октета IP
  IFS='.' read -r -a octets <<< "$1"
  for octet in "${octets[@]}"; do
    # Проверка на ведущие нули (например, 01, 001)
    if [[ "$octet" != "0" && "$octet" =~ ^0 ]]; then
      echoerr "Октет с ведущим нулём недопустим: $octet"
      return 1
    fi

    # Преобразуем явно в десятичное значение и проверим диапазон
    dec_octet=$((10#$octet))
    if ((dec_octet < 0 || dec_octet > 255)); then
      echoerr "Неверный диапазон октета: $octet"
      return 1
    fi
  done

  return 0
}

# - e-mail адрес
check_email() {
  # Если строка не является доменом
  if [[ ! "$1" =~ ^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$ ]]; then
    echoerr "Некорректный email: $1"
    return 1
  fi

  return 0
}

# - пароль
check_password() {
  # Проверка на пустой ввод
  if [ -z "$1" ]; then
    echoerr "Пароль не может быть пустым"
    return 1
  fi

  # Проверка длины пароля (минимум 6 символов)
  if [ "${#1}" -lt 6 ]; then
    echoerr "Пароль должен быть не короче 6 символов"
    return 1
  fi

  # Проверка наличия хотя бы одной буквы
  if ! echo "$1" | grep -q '[a-zA-Z]'; then
    echoerr "Пароль должен содержать хотя бы одну букву"
    return 1
  fi

  # Проверка наличия хотя бы одной цифры
  if ! echo "$1" | grep -q '[0-9]'; then
    echoerr "Пароль должен содержать хотя бы одну цифру"
    return 1
  fi

  return 0
}

# - порт
check_port() {
  # Проверка, является ли порт числом
  if ! [[ "$1" =~ ^[0-9]+$ ]]; then
    echoerr "Порт должен быть числом"
    return 1
  fi

  # Проверка диапазона порта (49152–65534)
  if [ "$1" -lt 49152 ] || [ "$1" -gt 65534 ]; then
    echoerr "Порт должен быть в диапазоне от 49152 до 65534"
    return 1
  fi

  # Проверка, занят ли порт
  if lsof -i :"$1" >/dev/null ; then
    echoerr "Порт $1 уже занят"
    return 1
  fi

  return 0
}


## Функции ввода, проверки данных:

# - имя домена
input_wg_host() {
  while true; do
    echomsg "Введите доменное имя этого сервера, например mydomain.com"
    echo "Если его нет просто нажмите клавишу Enter"
    read -rp " > Доменное имя: " wg_host
    
    # Проверка на пустой ввод
    if [ -z "$wg_host" ]; then
      # IP текущего сервера
      local public_ip

      # ip route (локальный интерфейс)
      public_ip=$(ip route get 1.1.1.1 2>/dev/null | awk '{for(i=1;i<=NF;i++) if ($i=="src") print $(i+1)}')

      # через DNS (OpenDNS)
      [ -z "$public_ip" ] && command -v dig >/dev/null && \
        public_ip=$(dig +short -4 myip.opendns.com @resolver1.opendns.com)

      # Проверка формата
      if [[ "$public_ip" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]]; then
        wg_host="$public_ip"
      else
        echoerr "Не удалось определить публичный IP"
        while true; do
          echomsg "Введите публичный IPv4 ардес этого сервера"
          read -rp "IPv4 этого сервера: " wg_host

          if check_IPv4 "$wg_host"; then
            break
          fi
        done
      fi

      echook "IPv4: $wg_host принят"
      break
    fi

    # Проверка имени
    if check_domain "$wg_host"; then
      echook "Доменное имя: $wg_host принято"
      break
    fi
  done
}

# - e-mail для полученя SSL сертификата домена
input_email() {
  if [[ "$is_domain" ]]; then
    while true; do
      echomsg "Введите e-mail для получения SSL сертификата домена $wg_host:"
      read -rp " > Ваш e-mail: "

      # Проверка ввода
      if check_email "$email"; then
        echook "E-mail: $email принят"
        break
      fi
    done
  fi
}

# - IPv4 адрес сервера shadowsocks
input_ss_ip() {
  while true; do
    echomsg "Введите IP адрес shadowsocks сервера, если его нет нажмите Enter:"
    read -r ss_ip
    
    # Проверка на пустой ввод
    if [ -z "$ss_ip" ]; then
      is_shadowsocks=""
      break
    fi

    # Проверка IPv4
    if check_IPv4 "$ss_ip"; then
      is_shadowsocks="true"
      echook "IPv4 shadowsocks: $ss_ip"
      break
    fi
  done
}

# - порт shadowsocks сервера
input_ss_port() {
  if [[ "$is_shadowsocks" ]]; then
    while true; do
      echomsg "Введите порт shadowsocks сервера $ss_ip:"
      read -r ss_port
      
      # Проверка порта
      if check_port "$ss_port"; then
        echook "Порт от shadowsocks сервера $ss_ip: $ss_port"
        break
      fi
    done
  fi
}

# - пароль shadowsocks сервера
input_ss_password() {
  if [[ "$is_shadowsocks" ]]; then
    while true; do
      echomsg "Пароль shadowsocks сервера $ss_ip:"
      read -rs ss_password
      
      # Проверка на пустой ввод
      if [ -z "$ss_password" ]; then
        echoerr "Пароль не может быть пустым"
        continue
      fi
      echook "Пароль shadowsocks сервера $ss_ip принят"
      break
    done
  fi
}

# - порт WireGuard сервера
input_wg_port() {
  while true; do
    echomsg "Введите порт WireGuard от 49152 до 65534"
    echo "(Для веб интерфейса будет увеличен на 1)"
    read -rp " > Порт WireGuard: " wg_port

    # Увеличиваем порт на 1 (для UI интерфейса)
    port=$((wg_port + 1))

    # Проверка портов
    if check_port "$wg_port" && check_port "$port"; then
      echook "Заданы порты:"
      echo " - WireGuard: $wg_port"
      echo " - Веб интерфейс: $port"
      # Cсылка на UI интерфейс wg-easy
      link_ui="http://$wg_host:$port"
      if [[ "$is_domain" ]]; then
        link_ui="https://$wg_host/$handle_path_ui/"
      fi
      break
    fi
  done

  if [[ "$is_shadowsocks" ]]; then
    while true; do
      echomsg "Введите порт WireGuard от 49152 до 65534"
      echo "(Для веб интерфейса будет увеличен на 1)"
      read -rp " > Порт WireGuard (shadowsocks прокси): " wg_port_ss
      
      # Увеличиваем порт на 1 (для UI интерфейса)
      port_ss=$((wg_port_ss + 1))

      # Проверка портов
      if check_port "$wg_port_ss" && check_port "$port_ss"; then
        echook "Заданы порты:"
        echo " - WireGuard (shadowsocks прокси): $wg_port_ss"
        echo " - Веб интерфейс (shadowsocks прокси): $port_ss"
        # Cсылка на UI интерфейс wg-easy, shadowsocks тунннель
        link_ui_ss="http://$wg_host:$port_ss"
        if [[ "$is_domain" ]]; then
          link_ui_ss="https://$wg_host/$handle_path_ui_ss/"
        fi
        break
      fi
    done
  fi
}

# - диапазон адресов для клиентов WireGuard
input_default_address() {
  local default_value="10.0.0.x"
  local default_value_ss="10.1.0.x"

  echomsg "Диапазон адресов клиентов WireGuard"
  echo "(нажмите Enter, чтобы оставить по умолчанию)"
  read -r -e -i "$default_value" default_address
  
  default_address=${default_address:-$default_value}
  echook "Задан диапазон адресов для клиентов: $default_address"

  if [[ "$is_shadowsocks" ]]; then
    echomsg "Диапазон адресов клиентов WireGuard через shadowsocks прокси"
    echo "(нажмите Enter, чтобы оставить по умолчанию)"
    read -r -e -i "$default_value_ss" default_address_ss
    default_address_ss=${default_address_ss:-$default_value_ss}
    echook "Задан диапазон адресов для клиентов WireGuard" 
    echo "(shadowsocks прокси): $default_address_ss"
  fi
}

# - пароль для входа в UI wg-easy
input_ui_password() {
  local password

  while true; do
    echomsg "Придумайте пароль для входа в веб-интерфейс (ввод скрыт)"
    read -rsp " > Пароль веб интерфейса: " password
    
    # Проверка и обработка пароля
    if check_password "$password"; then
      # Запрашиваем хеша пароля
      output_wgpw=$(docker run --rm -it ghcr.io/wg-easy/wg-easy wgpw "$password")
      # Извлекаем и экранируем хеш пароля
      password_hash=$(echo "$output_wgpw" | cut -d "'" -f2 | sed 's/\$/\$\$/g' | tr -d '\r')

      echook "Пароль веб интерфейса принят"
      break
    fi
  done
}

# Загрузка tun2socks v2.5.2
download_tun2socks() {
  if [[ "$is_shadowsocks" ]]; then
    echomsg "Загружаем tun2socks, с скриптом поднятия tun интерфейса"
    mkdir -p "$(dirname "$path_tun2socks")"
    curl -fsSL -o "$path_tun2socks" https://raw.githubusercontent.com/jinndi/wg-easy-bash/refs/heads/main/tun2socks
    chmod +x "$path_tun2socks"

    mkdir -p "$(dirname "$path_tun2socks_init")"
    curl -fsSL -o "$path_tun2socks_init" https://raw.githubusercontent.com/jinndi/wg-easy-bash/refs/heads/main/tun2socks-init.sh
    chmod +x "$path_tun2socks_init"
    echook "файлы загружены"

    # Проверка что оба файла загружены
    if [ -s "$path_tun2socks" ] && [ -s "$path_tun2socks_init" ]; then
      echook "Файлы загружены и готовы"
    else
      exiterr "Ошибка загрузки tun2socks файлов"
    fi
  fi
}

# Функция создания конфигов сервисов и служб
create_services_config() {
echomsg "Создаём конфиги Docker сервисов"

## wg-easy:
# - wg-easy дефолтный сервис docker compose
cat <<WG_EASY_SERVICE  > "$path_docker_compose_file"
services:
  wg-easy:
    environment:
      - LANG=ru
      - WG_HOST=$wg_host
      - PASSWORD_HASH=$password_hash
      - PORT=$port
      - WG_PORT=$wg_port
      - WG_MTU=1420
      - WG_PERSISTENT_KEEPALIVE=25
      - WG_DEFAULT_ADDRESS=$default_address
      - WG_DEFAULT_DNS=$default_dns
      - UI_TRAFFIC_STATS=true
    image: $wg_easy_image
    container_name: wg-easy
    hostname: wg-easy
    volumes:
      - $path_data_wg_dir/wg-easy:/etc/wireguard
    ports:
      - $wg_port:$wg_port/udp
      - $port:$port/tcp
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1

WG_EASY_SERVICE

# - wg-easy-ss сервис docker compose сервис wg-easy через tun2socks девайс shadowsocks прокси
if [[ "$is_shadowsocks" ]]; then
cat <<WG_EASY_SS_SERVICE >> "$path_docker_compose_file"
  wg-easy-ss:
    environment:
      - LANG=ru
      - WG_HOST=$wg_host
      - PASSWORD_HASH=$password_hash
      - PORT=$port_ss
      - WG_DEVICE=$ss_tun_name
      - WG_PORT=$wg_port_ss
      - WG_MTU=1420
      - WG_PERSISTENT_KEEPALIVE=25
      - WG_DEFAULT_ADDRESS=$default_address_ss
      - WG_DEFAULT_DNS=$default_dns
      - UI_TRAFFIC_STATS=true
      - WG_POST_UP=/sbin/tun2socks-init.sh
      - SS_TUN_NAME=$ss_tun_name
      - SS_IP=$ss_ip
      - SS_PORT=$ss_port
      - SS_PASSWORD=$ss_password
    image: $wg_easy_image
    container_name: wg-easy-ss
    hostname: wg-easy-ss
    volumes:
      - $path_data_wg_dir/wg-easy-ss:/etc/wireguard
      - $path_tun2socks:/sbin/tun2socks
      - $path_tun2socks_init:/sbin/tun2socks-init.sh
    ports:
      - $wg_port_ss:$wg_port_ss/udp
      - $port_ss:$port_ss/tcp
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices:
      - /dev/net/tun
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1

WG_EASY_SS_SERVICE
fi

## Caddy сервер (если указан домен):
if [[ "$is_domain" ]]; then
# - docker compose сервис
cat <<CADDY_SERVICE >> "$path_docker_compose_file"
  caddy:
    image: caddy
    container_name: caddy
    cap_add:
      - NET_ADMIN
    ports:
      - 443:443/tcp
      - 443:443/udp
    volumes:
      - $path_caddyfile:/etc/caddy/Caddyfile
      - $path_caddy_data:/data
      - $path_caddy_config:/config

CADDY_SERVICE

# - Caddyfile:
mkdir -p "$(dirname "$path_caddyfile")"

# -- открываем основной блок хоста
echo "$wg_host {" > "$path_caddyfile"
# -- указываем email для успешного получения сертификата
echo "  tls $email" >> "$path_caddyfile"
# -- reverse_proxy на UI wg-easy
cat <<CADDY_FILE_PROXY_WG_EASY >> "$path_caddyfile"

  handle_path /$handle_path_ui/* {
    reverse_proxy wg-easy:$port
  }
CADDY_FILE_PROXY_WG_EASY
# -- reverse_proxy на UI wg-easy (если IP адрес shadowsocks сервера задан)
if [[ "$is_shadowsocks" ]]; then
cat <<CADDY_FILE_PROXY_WG_EASY_SS >> "$path_caddyfile"

  handle_path /$handle_path_ui_ss/* {
    reverse_proxy wg-easy-ss:$port_ss
  }
CADDY_FILE_PROXY_WG_EASY_SS
fi

# -- закрываем основной блок хоста
echo "}" >> "$path_caddyfile"
fi

echook "Конфиги Docker сервисов созданы"
}

# Создание скриптов разрешения портов через iptables, при запуске/остановке службы
create_iptables_scripts(){
  # порты для открытия
  local ports=(
    "$wg_port udp"
    "$port tcp"
    "$port udp"
  )

  if [[ "$is_domain" ]]; then
    ports+=("443 tcp" "443 udp")
  fi

  if [[ "$is_shadowsocks" ]]; then
    ports+=("$wg_port_ss udp" "$port_ss tcp" "$port_ss udp")
  fi

  echomsg "Создание скриптов разрешения портов через iptables: 
  - при запуске служб разрешаем порты: 
  -- ${ports[*]}, запрещаем: 80 tcp
  - удаляем созданные правила при остановке"

  # Создать дирректорию для сохранения скриптов на запуск/остановку служб
  mkdir -p "$(dirname "$path_iptables_active_script")"
  mkdir -p "$(dirname "$path_iptables_delete_script")"

  # Очистка/создание файлов перед формированием конфигов
  : > "$path_iptables_active_script"
  : > "$path_iptables_delete_script"

  # Путь к iptables
  local iptables_path
  iptables_path=$(command -v iptables)
  if [[ $(systemd-detect-virt) == "openvz" ]] && readlink -f "$(command -v iptables)" | grep -q "nft" && hash iptables-legacy 2>/dev/null; then
    iptables_path=$(command -v iptables-legacy)
  fi

  # Формируем скрипты с правилами:
  {
    echo "#!/bin/bash"
    echo ""
  } | tee "$path_iptables_active_script" "$path_iptables_delete_script" > /dev/null

  for p in "${ports[@]}"; do
    read -r port proto <<< "$p"
    echo "$iptables_path -w 5 -I INPUT -p $proto --dport $port -j ACCEPT" >> "$path_iptables_active_script"
    echo "$iptables_path -w 5 -D INPUT -p $proto --dport $port -j ACCEPT" >> "$path_iptables_delete_script"
  done

  echo "$iptables_path -w 5 -I INPUT -p tcp --dport 80 -j DROP" >> "$path_iptables_active_script"
  echo "$iptables_path -w 5 -D INPUT -p tcp --dport 80 -j DROP" >> "$path_iptables_delete_script"

  # Завершаем скрипты
  echo "exit 0" | tee -a "$path_iptables_active_script" "$path_iptables_delete_script" > /dev/null

  # Делаем скрипты исполняемыми
  chmod +x "$path_iptables_active_script" "$path_iptables_delete_script"

  echook "Скрипты с правилами iptables созданы"
}

# Функция создания конфига sysctl настроек сети
create_sysctl_config(){
  echomsg "Создание конфига sysctl по пути $path_sysctl_config
  - разрешение forward ipv4
  - запрет определения туннеля
  - настройка сетевых буферов, ipv4 оптимизация
  - включение TCP BBR, если версия ядра >= 4.20" 

  # Создать дирректорию если нет
  mkdir -p "$(dirname "$path_sysctl_config")"

  # Загружаем конфиг
  curl -fsSL "$path_sysctl_config" https://raw.githubusercontent.com/jinndi/wg-easy-bash/refs/heads/main/sysctl.conf

  # Проверка что файл загружен
  if [ -f "$path_sysctl_config" ]; then
    # включение TCP BBR контроля перегрузки, если версия ядра >= 4.20
    if modprobe -q tcp_bbr \
      && printf '%s\n%s' "4.20" "$(uname -r)" | sort -C -V \
      && [ -f /proc/sys/net/ipv4/tcp_congestion_control ]; then
      cat >> "$path_sysctl_config" <<SYSCTL_CONF
# TCP BBR контроль перегрузки сети
net.core.default_qdisc = fq
net.ipv4.tcp_congestion_control = bbr
SYSCTL_CONF

    # Применяем полученный конфиг
    sysctl -e -q -p "$path_sysctl_config"

    echook "Конфиг sysctl создан и применен"
  else
    exiterr "Ошибка загрузки sysctl конфига"
  fi
}

# Функция создания systemd unit службы управления сервисами
create_systemd_unit(){
local working_dir
working_dir="$(dirname "$path_docker_compose_file")"

echomsg "Создание systemd unin службы"
cat <<SYSTEMD_UNIT > "$path_systemd_unit_file"
[Unit]
Description=wg-easy with iptables hooks via docker compose
After=network.target docker.service
Requires=docker.service

[Service]
Type=oneshot
RemainAfterExit=yes
WorkingDirectory=$working_dir
ExecStartPre=$path_iptables_active_script
ExecStart=/usr/bin/docker compose -f $path_docker_compose_file up -d --force-recreate
ExecStop=/usr/bin/docker compose -f $path_docker_compose_file down --remove-orphans
ExecStopPost=$path_iptables_delete_script
TimeoutStartSec=0

[Install]
WantedBy=multi-user.target
SYSTEMD_UNIT

systemctl daemon-reload
echook "Служба создана"
}

# Функция проверки что все сервисы запущены и работают корректно
is_all_ok_services() {
  # если файл docker compose не существует — false
  if [[ ! -e "$path_docker_compose_file" ]]; then
    return 1
  fi

  # проверка что systemd служба активна 
  if ! systemctl is-active --quiet wg-easy; then
    return 1
  fi

  # проверка наличия контейнеров
  local containers
  containers=$(docker compose -f "$path_docker_compose_file" ps -q)
  if [[ -z "$containers" ]]; then
    return 1
  fi

  # проверка каждого контейнера
  while read -r container; do
    local status
    status=$(docker inspect -f '{{.State.Running}} {{.State.ExitCode}}' "$container" 2>/dev/null)
    if [[ "$status" != "true 0" ]]; then
      return 1
    fi
  done <<< "$containers"

  return 0
}


# Функция запуска всех сервисов
start_services() {
  echomsg "Запускаем сервисы"

  # Запускаем докер контейнеры
  systemctl enable --now wg-easy
  #docker compose -f "$path_docker_compose_file" up -d --force-recreate
  local container status name
  for container in $(docker compose -f "$path_docker_compose_file" ps -q); do
    status=$(docker inspect -f '{{.State.Running}} {{.State.ExitCode}}' "$container" 2>/dev/null)
    name=$(docker inspect -f '{{.Name}}' "$container" 2>/dev/null | sed 's|^/||')
    if [[ "$status" != "true 0" ]]; then
      echoerr "Контейнер $name ($container) не работает! docker logs -f --tail 100 $name"
    fi
  done

  if ! systemctl is-active --quiet wg-easy; then
    echoerr "Запуск не удался"
  fi
}

# Функция остановки всех сервисов и служб
stop_services() {
  echomsg "Останавливаем сервисы"

  # Останавливаем и удаляем docker-контейнеры
  if [[ -f "$path_docker_compose_file" ]]; then
    systemctl disable --now wg-easy
    #docker compose -f "$path_docker_compose_file" down --remove-orphans || {
    #  echoerr "Ошибка при остановке контейнеров через docker compose"
    #}
    if systemctl is-active --quiet wg-easy; then
      echoerr "Остановка не удалась"
    fi
  else
    echoerr "Файл docker-compose не найден: $path_docker_compose_file"
  fi
}

# Функция переключения статуса активности сервисов
switch_active_services() {
  # Если все сервисы и службы работают
  if is_all_ok_services; then
    stop_services
  else
    start_services
  fi

  select_menu_option
}

# Функция перезапуска  сервисов
restart_services() {
  echomsg "Перезапускаем сервисы"
  systemctl restart wg-easy
  select_menu_option
}

# Функция установки приложения
install_services() {
  # проверка поддержки
  check_root
  check_shell
  check_kernel
  check_os
  check_os_ver
  check_container

  # приветсвие
  show_header
  read -n1 -r -p "Нажмите любую клавишу, чтобы начать установку..."

  # удаление предущей установки если была
  # и остались файлы после неудачной
  remove_install

  # создаем необходимы папки
  mkdir -p "$path_data_dir"
  mkdir -p "$(dirname "$path_script")"

  # перемещам текущий скрипт, добавляем на него права и ссылку
  mv "$(realpath "$0")" "$path_script"
  chmod +x "$path_script"
  ln -s "$path_script" "$path_script_link"

  # установка зависимостей
  install_pkgs

  # считывание вода пользователя
  input_wg_host
  input_email
  input_ss_ip
  input_ss_port
  input_ss_password
  input_wg_port
  input_default_address
  input_ui_password

  # загрузка tun2socks
  download_tun2socks

  # создание конфига докер сервисов
  create_services_config

  # создание скриптов iptables настроек
  create_iptables_scripts

  # создание скриптов sysctl конфига
  create_sysctl_config

  # создание systemd unit службы управления сервисами
  create_systemd_unit

  # запуск сервисов
  start_services

  echo 
  echo "Веб интерфейс: $link_ui"
  if [[ "$is_shadowsocks" ]]; then
    echo "Веб интерфейс (shadowsocks): $link_ui_ss"
  fi
  echo

  # отображение меню опций
  select_menu_option
}

# Функция подтверждения удаления приложения
remove_services() {
  echo
  local msg
  msg="Удалить приложение? [y/N]: "
  read -rp "$msg" remove

  until [[ "$remove" =~ ^[yYnNдДнН]*$ ]]; do
    echo "$remove: неверная опция."
    read -rp "$msg" remove
  done

  if [[ "$remove" =~ ^[yYnNдДнН]$ ]]; then
    remove_install "1"
    exit 0
  else
    select_menu_option
  fi
}

select_menu_option() {
  local select_option
  select_option="Выберите опцию:"
  show_header
  if is_all_ok_services; then
    echo "Статус: ✅ Все сервисы работают"
    echo "$select_option"
    echo "  1) Выключить"
  else
    echo "Статус: ❌ Не активно"
    echo "$select_option"
    echo "  1) Включить"
  fi
  echo "  2) Перезапустить"
  echo "  3) Удалить"
  echo "  4) Выход"

  read -rp "Опция: " option
  until [[ "$option" =~ ^[1-4]$ ]]; do
    echo "$option: неккоректное значение."
    read -rp "Опция: " option
  done

  case "$option" in
    1)
      switch_active_services
    ;;
    2)
      restart_services
    ;;
    3)
      remove_services
    ;;
    4)
      exit 0
    ;;
  esac
}

if [[ -d "$path_data_dir" ]]; then
  select_menu_option
else
  install_services
fi

$SHELL
