#!/bin/bash
#
# https://github.com/jinndi/wg-easy-bash
#
# Copyright (c) 2025 Jinndi <alncores@gmail.ru>
#
# Released under the MIT License, see the accompanying file LICENSE
# or https://opensource.org/licenses/MIT

## Пути исполняемых файлов
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

## Пути файлов:
# - папка в которую будет произведена установка
path_data_dir="$HOME/.wg-easy"
# - файл текущего скрипта
path_script="$path_data_dir/wg-easy"
# - ссылка на файл текущего скрипта
path_script_link="/usr/bin/wg-easy"
# - папка настроек wireguard
path_data_wg_dir="$path_data_dir/wireguard"
# - файл docker compose сервисов
path_docker_compose_file="$path_data_dir/services.yml"
# - файл настройки Caddy сервера
path_caddyfile="$path_data_dir/caddy/Caddyfile"
# - папка с данными  Caddy сервера
path_caddy_data="$path_data_dir/caddy/data"
# - папка с настройками Caddy сервера
path_caddy_config="$path_data_dir/caddy/config"
# - исполняемый файл shadowsocks прокси tun2socks
path_tun2socks="$path_data_dir/tun2socks"
# - файл настройки службы tun2socks
path_tun2socks_service=/etc/systemd/system/tun2socks.service
# - файл с портами которым выдали разрешения через ufw
path_save_ports="$path_data_dir/.ufw_ports.txt"

## Интернет интерфейсы:
# - по умолчанию (обычно eth0)
default_device_name="$(ip route | grep default | awk '{print $5}')"
# - shadowsocks прокси tun2socks
tun2socks_device_name="sstun"
tun2socks_device_addr="10.255.0.1/24"

## Пути в адресной строке браузера к UI интерфейсу (если указан домен):
# - по умолчанию
handle_path_ui="wg-easy"
# - для WireGuard через shadowsocks
handle_path_ui_ss="wg-easy-ss"

# DNS адреса по умолчанию для клиентов WireGuard (через запятую)
default_dns=1.1.1.1,8.8.8.8

## Объявление переменных задаваемых в процессе работы скрипта:
# - доменное имя либо адрес IP-адрес хоста
wg_host=""
# - e-mail адрес необходимый для получения SSL сертификата домена
email=""
# - tcp порт доступа к UI интерфейсу wg-easy
port=""
# - tcp порт доступа к UI интерфейсу wg-easy, shadowsocks тунннель
port_ss=""
# - udp порт WireGuard
wg_port=""
# - udp порт WireGuard, shadowsocks тунннель
wg_port_ss=""
# - диапазон IP-адресов клиентов WireGuard
default_address=""
# - диапазон IP-адресов клиентов WireGuard, shadowsocks тунннель
default_address_ss=""
# - IP-адрес shadowsocks сервера
ss_ip=""
# - порт shadowsocks сервера
ss_port=""
# - пароль к подключению по shadowsocks
ss_password=""
# - хеш пароля от UI интерфейса/ов wg-easy
password_hash=""
# - ссылка на UI интерфейс wg-easy
link_ui=""
# - ссылка на UI интерфейс wg-easy, shadowsocks тунннель
link_ui_ss=""

## Функции вывода сообщений:
# - шапка установщика
show_header() {
cat <<EOF

WG-EASY-BASH
Добро пожаловать в установщик!
GitHub: https://github.com/jinndi/wg-easy-bash

EOF
}
# - стандартное через задержку
echomsg() { sleep 1; echo "➡️ $1"; }
# - об успехе
echook() { echo " ✅ $1"; }
# - об ошибке
echoerr () { echo " ❌ $1"; }
# - об ошибке с выходом из скрипта
exiterr() { echo "❌ Ошибка: $1" >&2; exit 1; }


## Функции проверок возможности установки:
# - рут права
check_root() {
  if [ "$(id -u)" != 0 ]; then
    exiterr "Этот установщик должен быть запущен от имени root. Попробуйте 'sudo bash $0'"
  fi
}

# - способ запуска скрипта через bash а не sh
check_shell() {
  if readlink /proc/$$/exe | grep -q "dash"; then
    exiterr 'Этот установщик необходимо запускать с помощью «bash», а не «sh».'
  fi
}

# - вид дистрибутива ОС
check_os() {
  if grep -qs "ubuntu" /etc/os-release; then
    os="ubuntu"
    os_version=$(grep 'VERSION_ID' /etc/os-release | cut -d '"' -f 2 | tr -d '.')
  elif [[ -e /etc/debian_version ]]; then
    os="debian"
    os_version=$(grep -oE '[0-9]+' /etc/debian_version | head -1)
  else
    exiterr "Этот установщик поддерживает только дистрибутивы Ubuntu и Debian!"
  fi
}

# - версия дистрибутива ОС
check_os_ver() {
  if [[ "$os" == "ubuntu" && "$os_version" -lt 2004 ]]; then
    exiterr "Для использования этого установщика требуется Ubuntu 20.04 или более поздняя версия."
  fi
  if [[ "$os" == "debian" && "$os_version" -lt 11 ]]; then
    exiterr "Для использования этого установщика требуется Debian 11 или более поздняя версия."
  fi
}

# - поддержка версии ядра
check_kernel() {
  if [[ $(uname -r | cut -d "." -f 1) -eq 2 ]]; then
    exiterr "В системе установлено старое ядро, несовместимое с данным установщиком."
  fi
}

# - среда работы ОС
check_container() {
  if systemd-detect-virt -cq 2>/dev/null; then
    exiterr "Эта система работает внутри контейнера, который не поддерживается данным установщиком."
  fi
}


# Функция удаления предыдущих установок (без докера)
remove_install() {
  local is_show_info="$1"

  if [[ -n "$is_show_info" ]]; then
    echomsg "Удаляем предыдущую установку"
  fi

  # Остановка докер сервисов с удаление всех задействованных контейнеров и образов
  if [[ -e "$path_docker_compose_file" ]]; then
      docker compose -f "$path_docker_compose_file" down --remove-orphans --rmi all
  fi

  # Остановка и удаление tun2socks службы
  if [[ -e "$path_tun2socks_service" ]]; then
    systemctl stop tun2socks
    systemctl disable tun2socks
    rm -f "$path_tun2socks_service"
    systemctl daemon-reload
  fi

  # Удаление правил ранее заданных для портов (через файрвол ufw)
  if [[ -f "$path_save_port" ]]; then
    while read -r line; do
      action=$(echo "$line" | cut -d' ' -f1)
      rule=$(echo "$line" | cut -d' ' -f2)
      ufw delete "$action" "$rule"
    done < "$path_save_port"
  fi

  # Удаление ссылки на скрипт управления
  if [[ -L "$path_script_link" ]]; then
    rm -f "$path_script_link"
  fi

  # Удаление папки данных
  if [[ -d "$path_data_dir" ]]; then
    rm -rf "$path_data_dir"
  fi

  if [[ -n "$is_show_info" ]]; then
    echook "Файлы и службы/сервисы удалены"
  fi
}


# Функция установки необходимых пакетов программ
install_pkgs() {
  # Обновление пакетов
  echomsg "Обновление пакетов"
  apt update
  apt upgrade -y
  echook "Пакеты обновлены"

  # Установка зависимостей
  echomsg "Установка зависимостей ufw, curl, unzip, lsof, docker compose"
  apt install ufw curl unzip lsof -y
  echook "Зависимости установлены"

  # Установка и запуск докера если ранее не установлен 
  if ! docker compose version &> /dev/null; then
    echomsg "Установка docker"
    curl -sSL https://get.docker.com | sh
    echook "docker установлен"
  fi
  usermod -a -G docker "$USER"
  systemctl restart docker
}


## Фунции проверок введенных данных пользователем:

# - имя домена
check_domain() {
  # Если строка не является доменом
  if [[ ! "$1" =~ ^([a-zA-Z0-9]([a-zA-Z0-9-]*[a-zA-Z0-9])?\.)+[a-zA-Z]{2,}$ ]]; then
    if [[ -n "$1" ]]; then
      echoerr "Неккоректный адрес домена: $1"
    fi
    return 1
  fi

  return 0
}

# - IPv4 адрес
check_IPv4() {
  # Проверка на формат IPv4
  if [[ ! "$1" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]]; then
    echoerr "Это не IPv4: $input"
    return 1
  fi

  # Проверка на диапазон для каждого октета IP
  IFS='.' read -r -a octets <<< "$1"
  for octet in "${octets[@]}"; do
    if ((octet < 0 || octet > 255)); then
      echoerr "Неверный IPv4 адрес (не все октеты в пределах 0-255): $1"
      return 1
    fi
  done

  return 0
}

# - e-mail адрес
check_email() {
  # Если строка не является доменом
  if [[ ! "$1" =~ ^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$ ]]; then
    echoerr "Некорректный email: $1"
    return 1
  fi

  return 0
}

# - пароль
check_password() {
  # Проверка длины пароля (минимум 6 символов)
  if [ "${#1}" -lt 6 ]; then
    echoerr "Пароль должен быть не короче 6 символов"
    return 1
  fi

  # Проверка наличия хотя бы одной буквы
  if ! echo "$1" | grep -q '[a-zA-Z]'; then
    echoerr "Пароль должен содержать хотя бы одну букву"
    return 1
  fi

  # Проверка наличия хотя бы одной цифры
  if ! echo "$1" | grep -q '[0-9]'; then
    echoerr "Пароль должен содержать хотя бы одну цифру"
    return 1
  fi

  return 0
}

# - порт
check_port() {
  # Проверка, является ли порт числом
  if ! [[ "$1" =~ ^[0-9]+$ ]]; then
    echoerr "Порт должен быть числом"
    return 1
  fi

  # Проверка диапазона порта (1–65534)
  if [ "$1" -lt 1 ] || [ "$1" -gt 65534 ]; then
    echoerr "Порт должен быть в диапазоне от 1 до 65534"
    return 1
  fi

  # Проверка, занят ли порт
  if lsof -i :"$1" >/dev/null ; then
    echoerr "Порт $1 уже занят"
    return 1
  fi

  return 0
}


## Функции ввода, проверки данных:

# - имя домена
input_wg_host() {
  while true; do
    echomsg "Введите домен, например mydomain.com, который указывает по A записи на IP $wg_host, если его нет просто нажмите Enter:"
    read wg_host

    # Проверка на пустой ввод
    if [ -z "$wg_host" ]; then
      # IP текущего сервера
      wg_host=$(hostname -I | awk '{print $1}')
      echook "Используем в качестве хоста IP: $wg_host"
      break
    fi

    # Проверка имени
    if check_domain "$wg_host"; then
      echook "Домен для wg-easy: $wg_host"
      break
    fi
  done
}

# - e-mail для полученя SSL сертификата домена
input_email() {
  if check_domain "$wg_host"; then
    while true; do
      echomsg "Введите email для получения SSL сертификата домена $domain:"
      read email

      # Проверка ввода
      if check_email "$email"; then
        echook "Email для получения SSL сертификата: $email"
        break
      fi
    done
  fi
}

# - IPv4 адрес сервера shadowsocks
input_ss_ip() {
  while true; do
    echomsg "Введите IP адрес shadowsocks сервера, если его нет нажмите Enter:"
    read ss_ip

    # Проверка на пустой ввод
    if [ -z "$ss_ip" ]; then
      break
    fi

    # Проверка IPv4
    if check_IPv4 "$ss_ip"; then
      echook "IPv4 shadowsocks: $ss_ip"
      break
    fi
  done
}

# - порт shadowsocks сервера
input_ss_port() {
  if [[ -n "$ss_ip" ]]; then
    while true; do
      echomsg "Введите порт shadowsocks сервера $ss_ip:"
      read ss_port

      # Проверка порта
      if check_port "$ss_port"; then
        echook "Порт от shadowsocks сервера $ss_ip: $ss_port"
        break
      fi
    done
  fi
}

# - пароль shadowsocks сервера
input_ss_password() {
  if [[ -n "$ss_ip" ]]; then
    while true; do
      echomsg "Пароль shadowsocks сервера $ss_ip:"
      read -rs ss_password

      # Проверка на пустой ввод
      if [ -z "$ss_password" ]; then
        echoerr "Пароль не может быть пустым"
        continue
      fi
      echook "Пароль shadowsocks сервера $ss_ip принят"
      break
    done
  fi
}

# - порт WireGuard сервера
input_wg_port() {
  while true; do
    echomsg "Введите порт WireGuard (от 1 до 65534):"
    read wg_port

    # Увеличиваем порт на 1 (для UI интерфейса)
    port=$((wg_port + 1))

    # Проверка портов
    if check_port "$wg_port" && check_port "$port"; then
      echook "Порт для WireGuard: $wg_port"
      echook "Порт для UI интерфейса wg-easy: $port"
      # Cсылка на UI интерфейс wg-easy
      link_ui="http://$wg_host:$port"
      if check_domain "$wg_host"; then
        link_ui="https://$wg_host/$handle_path_ui"
      fi
      break
    fi
  done

  if [[ -n "$ss_ip" ]]; then
    while true; do
      echomsg "Введите порт WireGuard работающего через shadowsocks прокси (от 1 до 65534):"
      read wg_port_ss

      # Увеличиваем порт на 1 (для UI интерфейса)
      port_ss=$((wg_port_ss + 1))

      # Проверка портов
      if check_port "$wg_port_ss" && check_port "$port_ss"; then
        echook "Порт для WireGuard, shadowsocks прокси: $wg_port"
        echook "Порт для UI интерфейса wg-easy, shadowsocks прокси: $port"
        # Cсылка на UI интерфейс wg-easy, shadowsocks тунннель
        link_ui_ss="http://$wg_host:$port_ss"
        if check_domain "$wg_host"; then
          link_ui_ss="https://$wg_host/$handle_path_ui_ss"
        fi
        break
      fi
    done
  fi
}

# - диапазон адресов для клиентов WireGuard
input_default_address() {
  local default_value="10.0.0.x"
  local default_value_ss="10.1.0.x"

  echomsg "Диапазон адресов клиентов WireGuard (нажмите Enter, чтобы оставить по умолчанию):"
  read -e -i "$default_value" default_address
  default_address=${default_address:-$default_value}
  echook "Используем диапазон адресов для клиентов: $default_address"

  if [[ -n "$ss_ip" ]]; then
    echomsg "Диапазон адресов клиентов (WireGuard через shadowsocks прокси, нажмите Enter, чтобы оставить по умолчанию):"
    read -e -i "$default_value_ss" default_address_ss
    default_address_ss=${default_address_ss:-$default_value_ss}
    echook "Используем диапазон адресов для клиентов (WireGuard через shadowsocks прокси): $default_address_ss"
  fi
}

# - пароль для входа в UI wg-easy
input_ui_password() {
  local password

  while true; do
    echomsg "Введите сложный пароль для UI веб-интерфейса wg-easy:"
    read -rs password

    # Проверка на пустой ввод
    if [ -z "$password" ]; then
      echoerr "Пароль не может быть пустым"
      continue
    fi

    # Проверка и обработка пароля
    if check_password "$password"; then
      # Запрашиваем хеша пароля
      output_wgpw=$(docker run --rm -it ghcr.io/wg-easy/wg-easy wgpw "$password")
      # Извлекаем и экранируем хеш пароля
      password_hash=$(echo "$output_wgpw" | cut -d "'" -f2 | sed 's/\$/\$\$/g' | tr -d '\r')

      echook "Пароль принят"
      break
    fi
  done
}

# Функция создания конфигов сервисов и служб
create_configs() {
echomsg "Создаём конфиги сервисов"

## wg-easy:
# - wg-easy дефолтный сервис docker compose
cat <<WG_EASY_SERVICE  > "$path_docker_compose_file"
services:
  wg-easy:
    environment:
      - LANG=ru
      - WG_HOST=$wg_host
      - PASSWORD_HASH=$password_hash
      - PORT=$port
      - WG_DEVICE=$default_device_name
      - WG_PORT=$wg_port
      - WG_MTU=1420
      - WG_PERSISTENT_KEEPALIVE=25
      - WG_DEFAULT_ADDRESS=$default_address
      - WG_DEFAULT_DNS=$default_dns
      - UI_TRAFFIC_STATS=true
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    hostname: wg-easy
    volumes:
      - $path_data_wg_dir/wg-easy:/etc/wireguard
    ports:
      - $wg_port:$wg_port/udp
      - $port:$port/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
      - net.ipv4.conf.all.src_valid_mark=1

WG_EASY_SERVICE

# - wg-easy-ss сервис docker compose сервис wg-easy через tun2socks девайс shadowsocks прокси
cat <<WG_EASY_SS_SERVICE >> "$path_docker_compose_file"
  wg-easy-ss:
    environment:
      - LANG=ru
      - WG_HOST=$wg_host
      - PASSWORD_HASH=$password_hash
      - PORT=$port_ss
      - WG_DEVICE=$tun2socks_device_name
      - WG_PORT=$wg_port_ss
      - WG_MTU=1384
      - WG_PERSISTENT_KEEPALIVE=25
      - WG_DEFAULT_ADDRESS=$default_address_ss
      - WG_DEFAULT_DNS=$default_dns
      - UI_TRAFFIC_STATS=true
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy-ss
    hostname: wg-easy-ss
    volumes:
      - $path_data_wg_dir/wg-easy-ss:/etc/wireguard
    ports:
      - $wg_port_ss:$wg_port_ss/udp
      - $port_ss:$port_ss/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
      - net.ipv4.conf.all.src_valid_mark=1

WG_EASY_SS_SERVICE

## Caddy сервер (если указан домен):
if check_domain "$wg_host"; then
# - docker compose сервис
cat <<CADDY_SERVICE >> "$path_docker_compose_file"
  caddy:
    image: caddy
    container_name: caddy
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - 443:443/tcp
      - 443:443/udp
    volumes:
      - $path_caddyfile:/etc/caddy/Caddyfile
      - $path_caddy_data:/data
      - $path_caddy_config:/config

CADDY_SERVICE

# - Caddyfile:
# -- открываем основной блок хоста
echo "$wg_host {" > "$path_caddyfile"
# -- указываем email для успешного получения сертификата
echo "  tls $email" >> "$path_caddyfile"
# -- reverse_proxy на UI wg-easy
cat <<CADDY_FILE_PROXY_WG_EASY >> "$path_caddyfile"

  handle_path /$handle_path_ui/* {
    reverse_proxy wg-easy:$port
  }
CADDY_FILE_PROXY_WG_EASY
# -- reverse_proxy на UI wg-easy (если IP адрес shadowsocks сервера задан)
if [[ -n "$ss_ip" ]]; then
cat <<CADDY_FILE_PROXY_WG_EASY_SS >> "$path_caddyfile"

  handle_path /$handle_path_ui_ss/* {
    reverse_proxy wg-easy-ss:$port_ss
  }
CADDY_FILE_PROXY_WG_EASY_SS
fi

# -- закрываем основной блок хоста
echo "}" >> "$path_caddyfile"
fi

## Cлужба Tun2Socks (если IP адрес shadowsocks сервера задан)
if [[ -n "$ss_ip" ]]; then
cat <<TUN2SOCKS_SERVICE > "$path_tun2socks_service"
[Unit]
Description=Tun2Socks
Documentation=https://github.com/xjasonlyu/tun2socks
After=network.target

[Service]
Type=simple
User=root
ExecStartPre=-ip tuntap add mode tun dev ${tun2socks_device_name}
ExecStartPre=ip addr add ${tun2socks_device_addr} dev ${tun2socks_device_name}
ExecStartPre=ip link set dev ${tun2socks_device_name} up
ExecStart=${path_tun2socks} -interface ${default_device_name} \
                    -device ${tun2socks_device_name} \
                    -proxy ss://aes-256-gcm:${ss_password}@${ss_ip}:${ss_port}
ExecStopPost=-ip link set dev ${tun2socks_device_name} down
ExecStopPost=-ip link del dev ${tun2socks_device_name}

[Install]
WantedBy=multi-user.target
TUN2SOCKS_SERVICE
# перезапускаем демон systemctl чтобы увидеть новый сервис 
systemctl daemon-reload
fi

echook "Конфиги сохранены"
}

# Функция разрешения портов (через файрвол ufw)
allow_ports(){
  local ports=(
    "$wg_port/udp"
    "$port/tcp"
    "$port/udp"
  )

  if check_domain "$wg_host"; then
    ports+=("443/tcp" "443/udp")
  fi

  if [[ -n "$ss_ip" ]]; then
    ports+=("$wg_port_ss/udp" "$port_ss/tcp" "$port_ss/udp")
  fi

  # Очистка файла перед записью
  > "$path_save_ports"

  # Разрешаем порт ssh
  local ssh_port=$(grep -E '^\s*Port\s+[0-9]+' /etc/ssh/sshd_config | head -1 | awk '{print $2}')
  ufw allow ${ssh_port:-22}/tcp

  for p in "${ports[@]}"; do
    ufw allow "$p"
    echo "allow $p" >> "$save_ports_file"
  done

  ufw deny 80/tcp
  echo "deny 80/tcp" >> "$save_ports_file"

  ufw --force enable
  echook "Порты разрешены, список сохранён в $path_save_ports"
}

# Функция конфигурации sysctl (запрет двустороннего пинга, включение форвардинга)
config_sysctl() {
  # Запрет определения туннеля (двусторонний пинг)
  echomsg "Запрещаем определения туннеля (двусторонний пинг)"
  grep -q "^net/ipv4/icmp_echo_ignore_all" /etc/ufw/sysctl.conf || echo "net/ipv4/icmp_echo_ignore_all=1" | sudo tee -a /etc/ufw/sysctl.conf
  sed -i 's|^net/ipv4/icmp_echo_ignore_all.*|net/ipv4/icmp_echo_ignore_all=1|' /etc/ufw/sysctl.conf
  echook "Запрет установлен"

  # Включение ip_forward
  echomsg "Включаем форвардинг в /etc/sysctl.conf"
  # проверяем, существует ли строка, начинающаяся с net.ipv4.ip_forward
  if grep -q '^net.ipv4.ip_forward' /etc/sysctl.conf; then
    # если строка существует, заменяем ее на net.ipv4.ip_forward=1
    sed -i 's/^net\.ip\.v4\.ip_forward.*/net.ipv4.ip_forward=1/' /etc/sysctl.conf
  else
    # если строка не существует, добавляем ее в конец файла
    echo 'net.ipv4.ip_forward=1' | sudo tee -a /etc/sysctl.conf
  fi
  # проверяем, существует ли строка, начинающаяся с net.ipv6.conf.all.forwarding
  if grep -q '^net.ipv6.conf.all.forwarding' /etc/sysctl.conf; then
    # если строка существует, заменяем ее на net.ipv6.conf.all.forwarding=1
    sed -i 's/^net\.ipv6\.conf\.all\.forwarding.*/net.ipv6.conf.all.forwarding=1/' /etc/sysctl.conf
  else
    # если строка не существует, добавляем ее в конец файла
    echo 'net.ipv6.conf.all.forwarding=1' | sudo tee -a /etc/sysctl.conf
  fi

  # применяем изменения
  ufw reload
  sysctl -p

  echook "Форвардинг включен"
}

# Загрузка tun2socks v2.5.2
download_tun2socks() {
  if [[ -n "$ss_ip" ]]; then
    # Скачиваем tun2socks
    echomsg "Скачиваем tun2socks"
    mkdir -p "$(dirname "$path_tun2socks")"
    curl -L -o "$path_tun2socks" https://raw.githubusercontent.com/jinndi/wg-easy-bash/refs/heads/main/tun2socks
    chmod +x "$path_tun2socks"
    echook "tun2socks скачен"
  fi
}

# Функция проверки что все сервисы запущены и работают корректно
is_all_ok_services() {
  # если файл docker compose не существует то false
  if ! [[ -e "$path_docker_compose_file" ]]; then
    return  1
  fi

  # контейнеры docker указанные в docker compose файле
  for container in $(docker compose -f "$path_docker_compose_file" ps -q); do
    local status=$(docker inspect -f '{{.State.Running}} {{.State.ExitCode}}' "$container")
    if [[ "$status" != "true 0" ]]; then
      return  1
    fi
  done

  # служба tun2socks если она существует 
  if [[ -e "$path_tun2socks_service" ]]; then
    if ! systemctl is-active --quiet tun2socks; then
      return  1
    fi
  fi

  return 0
}


# Функция запуска всех сервисов и служб
start_services() {
  # Запускаем с автозапуском службу tun2socks если она существует
  if [[ -e "$path_tun2socks_service" ]]; then
    systemctl enable --now tun2socks
    if ! systemctl is-active --quiet tun2socks; then
      echoerr "Ошибка запуска tun2socks службы! Наберите 'journalctl -u tun2socks -n 100' для просмотра лога"
    fi
  fi

  # Запускаем докер контейнеры
  docker compose -f "$path_docker_compose_file" up
  for container in $(docker compose -f "$path_docker_compose_file" ps -q); do
    local status=$(docker inspect -f '{{.State.Running}} {{.State.ExitCode}}' "$container")
    if [[ "$status" != "true 0" ]]; then
      echoerr "Контейнер $container не работает! Наберите 'docker logs -f --tail 100 $container' для просмотра лога"
    fi
  done
}

# Функция остановки всех сервисов и служб
stop_services() {
  # Останавливаем и удаляем докер контейнеры
  docker compose -f "$path_docker_compose_file" down --remove-orphans
  for container in $(docker compose -f "$path_docker_compose_file" ps -a -q 2>/dev/null); do
    if docker inspect "$container" >/dev/null 2>&1; then
      echoerr "Контейнер $container не остановлен! Наберите 'docker logs -f --tail 100 $container' для просмотра лога"
    fi
  done

  # Останавливаем и выключаем службу tun2socks если она существует
  if [[ -e "$path_tun2socks_service" ]]; then
    systemctl stop tun2socks
    systemctl disable tun2socks
    if systemctl is-active --quiet tun2socks; then
      echoerr "Ошибка остановки tun2socks службы! Наберите 'journalctl -u tun2socks -n 100' для просмотра лога"
    fi
  fi
}

# Функция переключения статуса активности сервисов/служб
switch_active_services() {
  # Если все сервисы и службы работают
  if is_all_ok_services; then
    stop_services
  else
    start_services
  fi

  select_menu_option
}

# Функция установки приложения
install_services() {
  # проверка поддержки
  check_root
  check_shell
  check_kernel
  check_os
  check_os_ver
  check_container

  # приветсвие
  show_header
  read -n1 -r -p "Нажмите любую клавишу, чтобы начать установку..."

  # удаление предущей установки если была
  # и остались файлы после неудачной
  remove_install

  # создаем необходимы папки
  mkdir -p "$path_data_dir"
  mkdir -p "$(dirname "$path_script")"

  # перемещам текущий скрипт, добавляем на него права и ссылку
  mv "$(realpath "$0")" "$path_script"
  chmod +x "$path_script"
  ln -s "$path_script" "$path_script_link"

  # установка зависимостей
  install_pkgs

  # считывание вода пользователя
  input_wg_host
  input_email
  input_ss_ip
  input_ss_port
  input_ss_password
  input_wg_port
  input_default_address
  input_ui_password

  # создание конфигов
  create_configs
  # разрешение портов
  allow_ports
  # конфигурация sysctl
  config_sysctl
  # загрузка tun2socks
  download_tun2socks

  # запуск сервисов
  start_services

  # отображение меню опций
  select_menu_option
}

# Функция подтверждения удаления приложения
remove_services() {
  echo

  local msg="Удалить приложение? [y/N]: "
  read -rp "$msg" remove

  until [[ "$remove" =~ ^[yYnN]*$ ]]; do
    echo "$remove: неверная опция."
    read -rp "$msg" remove
  done

  if [[ "$remove" =~ ^[yY]$ ]]; then
    remove_install "1"
    exit 0
  else
    select_menu_option
  fi
}

select_menu_option() {
  local select_option="Выберите опцию:"
  
  if is_all_ok_services; then
    echo "Статус: ✅ Все сервисы работают"
    echo
    echo "$select_option"
    echo "   1) Выключить"
  else
    echo "Статус: ❌ Не активно"
    echo
    echo "$select_option"
    echo "   1) Включить"
  fi
  echo "   2) Удалить"
  echo "   3) Выход"

  read -rp "Опция: " option
  until [[ "$option" =~ ^[1-5]$ ]]; do
    echo "$option: неккоректное значение."
    read -rp "Опция: " option
  done

  case "$option" in
    1)
      switch_active_services
    ;;
    2)
      remove_services
    ;;
    3)
      exit 0
    ;;
  esac
}

if [[ -d "$path_data_dir" ]]; then
  select_menu_option
else
  install_services
fi

$SHELL
