#!/bin/bash

# Обновление библиотек
echo "Обновление пакетов"
apt update >/dev/null 2>&1
apt upgrade -y >/dev/null 2>&1
echo " Ок. Пакеты обновлены"

# Очистка предыдущих установок
if [[ -e "wg.yml" ]]; then
    # Останавливаем wg сервисы
    docker compose -f wg.yml down --remove-orphans >/dev/null 2>&1
fi
rm -f /root/wg-easy-bash /root/wg.yml /root/Caddyfile >/dev/null 2>&1
rm -f /root/run-wg /root/stop-wg /root/rerun-wg >/dev/null 2>&1
rm -rf /root/.wg-easy >/dev/null 2>&1

# Установка необходимых пакетов и запуск служб
sleep 1 && echo "Установка необходимых пакетов"
apt install ufw apparmor apparmor-utils nano -y >/dev/null 2>&1
ufw --force enable >/dev/null 2>&1
curl -sSL https://get.docker.com | sh >/dev/null 2>&1
usermod -a -G docker "$USER"
service docker start >/dev/null 2>&1
echo " Ок. Пакеты установлены"

# Загрузка образа wg-easy
sleep 1 && echo "Загрузка образа wg-easy"
docker pull ghcr.io/wg-easy/wg-easy >/dev/null 2>&1
echo " Ок. Образ wg-easy загружен"

# Получение переменных ip адреса хоста для конфига контейнера wg-easy
wg_host=$(hostname -I | awk '{print $1}')
server_ip="$wg_host"

# Функция для проверки имени домена
check_domain() {
    local domain="$1"

    # Если строка не является доменом
    if [[ ! $domain =~ ^([a-zA-Z0-9]([a-zA-Z0-9-]*[a-zA-Z0-9])?\.)+[a-zA-Z]{2,}$ ]]; then
        sleep 1 && echo " Ошибка: Это не домен: $domain"
        return 1
    fi

    return 0
}

# Функция для проверки адреса email
check_email() {
    local email="$1"

    # Если строка не является доменом
    if [[ ! $email =~ ^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$ ]]; then
        sleep 1 && echo " Ошибка: Некорректный email: $domain"
        return 1
    fi

    return 0
}

# Функция для проверки пароля
check_password() {
    local password="$1"

    # Проверка длины пароля (минимум 6 символов)
    if [ "${#password}" -lt 6 ]; then
        sleep 1 && echo " Ошибка: Пароль должен быть не короче 6 символов"
        return 1
    fi

    # Проверка наличия хотя бы одной буквы
    if ! echo "$password" | grep -q '[a-zA-Z]'; then
        sleep 1 && echo " Ошибка: Пароль должен содержать хотя бы одну букву"
        return 1
    fi

    # Проверка наличия хотя бы одной цифры
    if ! echo "$password" | grep -q '[0-9]'; then
        sleep 1 && echo " Ошибка: Пароль должен содержать хотя бы одну цифру"
        return 1
    fi

    return 0
}

# Функция для проверки порта
check_port() {
    local wg_port="$1"

    # Проверка, является ли порт числом
    if ! [[ "$wg_port" =~ ^[0-9]+$ ]]; then
        sleep 1 && echo " Ошибка: Порт должен быть числом"
        return 1
    fi

    # Проверка диапазона порта (1000–65534)
    if [ "$wg_port" -lt 1000 ] || [ "$wg_port" -gt 65534 ]; then
        sleep 1 && echo " Ошибка: Порт должен быть в диапазоне от 49152 до 65534"
        return 1
    fi

    return 0
}

# Цикл для ввода имени домена
while true; do
   sleep 1 && echo "Введите домен, например mydomain.com, который указывает по A записи на ip $server_ip, если его нет просто нажмите Enter:"
   read domain

    # Проверка на пустой ввод
    if [ -z "$domain" ]; then
        break
    fi

    # Проверка имени
    if check_domain "$domain"; then
        # Переопределяем wg_host
        wg_host="$domain"
        sleep 1 && echo " Ок. Домен для WireGuard: $wg_host"
        # Загрузка образа caddy
        sleep 1 && echo "Загрузка образа caddy"
        docker pull caddy >/dev/null 2>&1
        echo " Ок. Образ caddy загружен"
        break
    else
        echo "Попробуйте снова"
    fi
done

# Цикл ввода email для полученя SSL сертификата, если ранее указан домен 
if [[ -n "$domain" ]]; then
  while true; do
     sleep 1 && echo "Введите email для получения SSL сертификата домена $domain:"
     read email

      # Проверка ввода
      if check_email "$email"; then
          echo " Ок. Email для получения SSL сертификата: $email"
          break
      else
          echo "Попробуйте снова"
      fi
  done
fi

# Цикл для ввода пароля
while true; do
    sleep 1 && echo "Введите сложный пароль для веб интерфейса:"
    read -rs password

    # Проверка на пустой ввод
    if [ -z "$password" ]; then
        sleep 1 && echo " Ошибка: Пароль не может быть пустым"
        continue
    fi

    # Проверка и обработка пароля
    if check_password "$password"; then
        # Запрашиваем хеша пароля
        output_wgpw=$(docker run --rm -it ghcr.io/wg-easy/wg-easy wgpw "$password")
        # Извлекаем и экранируем хеш пароля
        password_hash=$(echo "$output_wgpw" | cut -d "'" -f2 | sed 's/\$/\$\$/g' | tr -d '\r')

        sleep 1 && echo " Ok. Пароль принят"
        break
    else
        echo "Попробуйте снова"
    fi
done

# Цикл для ввода порта
while true; do
    sleep 1 && echo "Введите порт (от 1000 до 65534):"
    read wg_port

    # Проверка порта
    if check_port "$wg_port"; then
        # Увеличиваем порт на 1
        port=$((wg_port + 1))
        echo " Ок. Порт для WireGuard: $wg_port"
        echo " Ок. Порт для веб интерфейста: $port"
        sleep 1
        break
    else
        echo "Попробуйте снова"
    fi
done

# Ввод диапазона адресов для клиентов wg
default_value="10.0.0.x"
sleep 1 && echo "Введите диапазон адресов клиентов (Enter, если не знаете зачем):"
read -e -i "$default_value" def_address
# Если пользователь ничего не ввёл (просто нажал Enter), используем значение по умолчанию
def_address=${def_address:-$default_value}
sleep 1 & echo "Используем диапазон адресов для клиентов: $def_address"

# Задаем значение для wg_easy_tcp_port
wg_easy_tcp_port=""
if [[ -z "$domain" ]]; then
   wg_easy_tcp_port=" - $port:$port/tcp"
fi

# Сохраняем  конфиги
sleep 1 && echo "Сохраняем конфиги в домашней директории"
cd || exit

# Сохраняем  конфиг на запуск wg
cat <<WG_YML > "wg.yml"
services:
  wg-easy:
    environment:
      - LANG=ru
      - WG_HOST=$wg_host
      - PASSWORD_HASH=$password_hash
      - PORT=$port
      - WG_PORT=$wg_port
      - WG_MTU=1420
      - WG_PERSISTENT_KEEPALIVE=25
      - WG_DEFAULT_ADDRESS=$def_address
      - WG_DEFAULT_DNS=1.1.1.1,8.8.8.8
      - UI_TRAFFIC_STATS=true
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    hostname: wg-easy
    volumes:
      - $PWD/.wg-easy:/etc/wireguard
    ports:
      - $wg_port:$wg_port/udp
     $wg_easy_tcp_port
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1

WG_YML

# Cсылка на WEB UI по умолчанию
link_ui="http://$wg_host:$port"

# Если доменное имя задано
if [[ -n "$domain" ]]; then
# добавляем сервис Caddy в wg.yml
cat <<CADDY_SERVICES >> "wg.yml"
  caddy:
    image: caddy
    container_name: caddy
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
    name: caddy_data
  caddy_config:
    name: caddy_config
CADDY_SERVICES

# добавляем Caddyfile файл для настройки reverse_proxy и редиректа на https
cat <<CADDY_FILE > "Caddyfile"
$domain {
  tls $email
  reverse_proxy wg-easy:$port
}
CADDY_FILE

# переопределяем link_ui
link_ui="https://$wg_host"
fi

# Сохраняем  конфиг на запуск wg
cat <<RUN_CONFIG > "run-wg"
#!/bin/sh
echo "run-wg: Запускаем wg-easy"
docker compose -f wg.yml up -d
echo "run-wg: Ok. 🎉 wg-easy запущен $link_ui"
RUN_CONFIG

# Сохраняем  конфиг на остановку wg
cat <<STOP_CONFIG > "stop-wg"
#!/bin/sh
echo "stop-wg: Останавливаем wg-easy"
docker compose -f wg.yml down --remove-orphans
echo "stop-wg: Ok. wg-easy остановлен"
STOP_CONFIG

# Сохраняем  конфиг на перезапуск wg
cat <<RERUN_CONFIG > "rerun-wg"
#!/bin/sh
echo "rerun-wg: Перезапускаем wg-easy"
./stop-wg 
./run-wg
echo "rerun-wg: Ok. wg-easy перезапущен"
RERUN_CONFIG

# Даём права на запуск конфигов управления docker-compose
chmod +x run-wg stop-wg rerun-wg

sleep 1 && echo " Ок. Конфиги сохранены"

# Разрешение портов через файрвол ufw
sleep 1 && echo "Разрешаем порты 22/tcp 80/tcp, $port/tcp, $port/upd, $wg_port/upd через файрвол ufw"
if [[ -n "$domain" ]]; then
    port="443"
    ufw allow "80/tcp" >/dev/null 2>&1
    ufw allow "$port/udp" >/dev/null 2>&1
fi
ufw allow ssh >/dev/null 2>&1
ufw allow "$port/tcp" >/dev/null 2>&1
ufw allow "$wg_port/udp" >/dev/null 2>&1
sleep 1 && echo " Ок. Порты разрешены"

# Запрет определения туннеля (двусторонний пинг)
sleep 1 && echo "Запрещаем определения туннеля (двусторонний пинг)"
sed -i 's|^net/ipv4/icmp_echo_ignore_all=.*|net/ipv4/icmp_echo_ignore_all=1|' /etc/ufw/sysctl.conf >/dev/null 2>&1
ufw reload >/dev/null 2>&1
sleep 1 && echo " Ок. Запрет установлен"

# Запуск wg-easy
./run-wg

$SHELL
